#ifndef MACHINE_CONTEXT_H
#define MACHINE_CONTEXT_H

/*
 * machine_context.h
 *
 * AUTO-GENERATED by sysmlc statix backend from state def 'Machine'. DO NOT EDIT.
 */

#include "sc/sc_types.h"

typedef struct machine_context_s {
    uint8_t _unused; /* no attributes in this model */
} machine_context_t;

#endif /* MACHINE_CONTEXT_H */
