/*
 * sm02/machine.c
 *
 * AUTO-GENERATED by sysmlc statix backend from state def 'SM02::Machine'. DO NOT EDIT.
 */

#include "sm02/machine.h"

/* Static state and transition tables (file-local). */
static const sc_state_def_t states[] = {
    {SC_ACTION_NONE, SC_ACTION_NONE},
    {SC_ACTION_NONE, SC_ACTION_NONE},
};

static const sc_transition_t transitions[] = {
    {SM02_MACHINE_STATE_IDLE, SM02_MACHINE_EVENT_TICK, SC_GUARD_NONE, SC_ACTION_NONE, SM02_MACHINE_STATE_RUNNING},
};

static const sc_machine_t machine_def = {
    transitions,
    states,
    (uint16_t)(sizeof(transitions) / sizeof(transitions[0])),
    SM02_MACHINE_STATE_COUNT,
    SM02_MACHINE_STATE_IDLE,
};

/* Generated guard/action dispatch. */
static bool guard_eval(sc_guard_id_t guard_id, const sc_runtime_t *runtime, const sc_event_t *event)
{
    (void)runtime;
    (void)event;
    (void)guard_id;
    return false;
}

static sc_status_t action_exec(sc_action_id_t action_id, sc_runtime_t *runtime, const sc_event_t *event)
{
    (void)runtime;
    (void)event;
    (void)action_id;
    return SC_STATUS_OK;
}

void sm02_machine_context_init(sm02_machine_context_t *ctx)
{
    if (ctx == NULL) {
        return;
    }
    *ctx = (sm02_machine_context_t){0};
}

const char *sm02_machine_state_name(sc_state_id_t state)
{
    switch (state) {
    case SM02_MACHINE_STATE_IDLE:
        return "idle";
    case SM02_MACHINE_STATE_RUNNING:
        return "running";
    case SC_STATE_INVALID:
        return "SC_STATE_INVALID";
    default:
        return "SC_STATE_UNKNOWN";
    }
}

const char *sm02_machine_event_name(sc_event_id_t event)
{
    switch (event) {
    case SM02_MACHINE_EVENT_TICK:
        return "Tick";
    case SC_EVENT_COMPLETION:
        return "SC_EVENT_COMPLETION";
    case SC_EVENT_INVALID:
        return "SC_EVENT_INVALID";
    default:
        return "SC_EVENT_UNKNOWN";
    }
}

/* Instantiate the shared dispatch for this machine. */
#define SC_MACHINE_PREFIX sm02_machine
#define SC_MACHINE_DEF machine_def
#define SC_MACHINE_GUARD guard_eval
#define SC_MACHINE_ACTION action_exec
#include "sc/sc_machine.h"
