#ifndef SM02_MACHINE_H
#define SM02_MACHINE_H

/*
 * sm02/machine.h
 *
 * AUTO-GENERATED by sysmlc statix backend from state def 'SM02::Machine'. DO NOT EDIT.
 */

#include "sc/sc_runtime.h"

#ifdef __cplusplus
extern "C" {
#endif

/// @brief Generated state identifiers.
typedef enum sm02_machine_state_e {
    SM02_MACHINE_STATE_IDLE = 0, ///< @brief State 'idle'.
    SM02_MACHINE_STATE_RUNNING = 1 ///< @brief State 'running'.
} sm02_machine_state_t;

#define SM02_MACHINE_STATE_COUNT 2u

/// @brief Generated signal event identifiers.
typedef enum sm02_machine_event_e {
    SM02_MACHINE_EVENT_TICK = 1 ///< @brief Signal event 'Tick'.
} sm02_machine_event_t;

/// @brief Generated guard identifiers.
/* (none defined in this model) */

/// @brief Generated action identifiers.
/* (none defined in this model) */


#define SM02_MACHINE_QUEUE_CAPACITY 8u
#define SM02_MACHINE_ACTIVE_CAPACITY 1u

/// @brief Generated context for SM02::Machine.
typedef struct sm02_machine_context_s {
    uint8_t _unused; ///< @brief Placeholder for empty context.
} sm02_machine_context_t;

/// @brief Runtime instance for SM02::Machine.
typedef struct sm02_machine_s {
    sc_runtime_t runtime;
    sc_activation_t active[SM02_MACHINE_ACTIVE_CAPACITY];
} sm02_machine_t;

/// @brief Initialize a generated context object with model default values.
/// @param ctx Context object to initialize.
void sm02_machine_context_init(sm02_machine_context_t *ctx);

/// @brief Initialize a statechart instance and enter its initial state.
/// @param sm Statechart instance to initialize.
/// @param ctx Context object owned by the caller.
/// @return SC_STATUS_OK on success, or an error status.
sc_status_t sm02_machine_init(sm02_machine_t *sm, sm02_machine_context_t *ctx);

/// @brief Dispatch one event into the statechart.
/// @param sm Statechart instance receiving the event.
/// @param event Event to dispatch.
/// @return SC_STATUS_OK if a transition fired, SC_STATUS_NO_TRANSITION if none matched, or an error status.
sc_status_t sm02_machine_dispatch(sm02_machine_t *sm, const sc_event_t *event);

/// @brief Dispatch one no-payload event by id.
/// @param sm Statechart instance receiving the event.
/// @param event_id Event identifier to dispatch.
/// @return SC_STATUS_OK if a transition fired, SC_STATUS_NO_TRANSITION if none matched, or an error status.
sc_status_t sm02_machine_post(sm02_machine_t *sm, sc_event_id_t event_id);

/// @brief Return the currently active state.
/// @param sm Statechart instance to inspect.
/// @return Active state id, or SC_STATE_INVALID before initialization.
sc_state_id_t sm02_machine_get_state(const sm02_machine_t *sm);

/// @brief Whether the machine reached a root-level final state (terminated).
/// @param sm Statechart instance to inspect.
/// @return true if the active leaf is a root-scope final state.
bool sm02_machine_is_final(const sm02_machine_t *sm);

/// @brief Number of currently active true leaves.
/// @param sm Statechart instance to inspect.
/// @return Count of active true leaves, or 0 before initialization.
sc_state_id_t sm02_machine_active_count(const sm02_machine_t *sm);

/// @brief The k-th currently active true leaf, in ascending slot order.
/// @param sm Statechart instance to inspect.
/// @param index Which active leaf to return, 0 <= index < sm02_machine_active_count(sm).
/// @return The index-th active leaf, or SC_STATE_INVALID if out of range.
sc_state_id_t sm02_machine_active_state(const sm02_machine_t *sm, sc_state_id_t index);

/// @brief Return a stable name for a generated state id.
/// @param state State identifier to name.
/// @return Static non-NULL state name.
const char *sm02_machine_state_name(sc_state_id_t state);

/// @brief Return a stable name for a generated event id.
/// @param event Event identifier to name.
/// @return Static non-NULL event name.
const char *sm02_machine_event_name(sc_event_id_t event);

#ifdef __cplusplus
}
#endif

#endif /* SM02_MACHINE_H */
