/*
 * machine_statechart_config.c
 *
 * AUTO-GENERATED by sysmlc statix backend from state def 'Machine'. DO NOT EDIT.
 */

#include "machine_statechart_config.h"

/* Per-state entry/exit action table (indexed by state id). */
static const sc_state_def_t machine_states[] = {
    {SC_ACTION_NONE, SC_ACTION_NONE},
    {SC_ACTION_NONE, SC_ACTION_NONE},
};

/* Transition rows: {source, event, guard, action, target}. */
static const sc_transition_t machine_transitions[] = {
    {MACHINE_STATE_IDLE, MACHINE_EVENT_TICK, SC_GUARD_NONE, SC_ACTION_NONE, MACHINE_STATE_RUNNING},
};

const sc_machine_t machine_statechart_machine = {
    machine_transitions,
    machine_states,
    (uint16_t)(sizeof(machine_transitions) / sizeof(machine_transitions[0])),
    MACHINE_STATE_COUNT,
    MACHINE_STATE_IDLE,
};
