/*
 * sm02/machine_runner.c
 *
 * AUTO-GENERATED by sysmlc statix backend from state def 'SM02::Machine'. DO NOT EDIT.
 */

#include "sm02/machine.h"

#include <stdio.h>
#include <string.h>

static bool sm02_machine_event_from_name(const char *name, sc_event_id_t *event_id)
{
    if ((name == NULL) || (event_id == NULL)) {
        return false;
    }
    if (strcmp(name, "Tick") == 0) {
        *event_id = SM02_MACHINE_EVENT_TICK;
        return true;
    }
    return false;
}

int main(int argc, char **argv)
{
    sm02_machine_context_t ctx;
    sm02_machine_t sm;
    sc_status_t status;
    int i;

    sm02_machine_context_init(&ctx);
    status = sm02_machine_init(&sm, &ctx);
    (void)printf("init status=%s state=%s final=%d\n", sc_status_str(status),
                 sm02_machine_state_name(sm02_machine_get_state(&sm)), (int)sm02_machine_is_final(&sm));
    if (status != SC_STATUS_OK) {
        return 1;
    }

    for (i = 1; i < argc; ++i) {
        sc_event_id_t event_id = SC_EVENT_INVALID;
        if (!sm02_machine_event_from_name(argv[i], &event_id)) {
            (void)fprintf(stderr, "unknown event: %s\n", argv[i]);
            return 2;
        }
        status = sm02_machine_post(&sm, event_id);
        (void)printf("event %s status=%s state=%s final=%d\n", argv[i],
                     sc_status_str(status), sm02_machine_state_name(sm02_machine_get_state(&sm)), (int)sm02_machine_is_final(&sm));
        if ((status != SC_STATUS_OK) && (status != SC_STATUS_NO_TRANSITION)) {
            return 1;
        }
    }
    return 0;
}
