/*
 * machinefiringorder_actions.c
 *
 * AUTO-GENERATED by sysmlc statix backend from state def 'MachineFiringOrder'. DO NOT EDIT.
 */

#include "machinefiringorder_statechart_ids.h"
#include "machinefiringorder_context.h"
#include "sc/sc_runtime.h"

bool sc_guard_eval(sc_guard_id_t guard_id, const sc_runtime_t *runtime, const sc_event_t *event)
{
    (void)runtime;
    (void)event;
    (void)guard_id;
    return false;
}

sc_status_t sc_action_exec(sc_action_id_t action_id, sc_runtime_t *runtime, const sc_event_t *event)
{
    machinefiringorder_context_t *ctx = (machinefiringorder_context_t *)runtime->user_data;
    (void)event;
    if (ctx == NULL) { return SC_STATUS_INVALID_ARGUMENT; }
    switch (action_id) {
    case MACHINEFIRINGORDER_ACTION_A_EXIT:
        ctx->seq = ctx->seq + 1;
        ctx->exitAt = ctx->seq;
        return SC_STATUS_OK;
    case MACHINEFIRINGORDER_ACTION_B_ENTRY:
        ctx->seq = ctx->seq + 1;
        ctx->entryAt = ctx->seq;
        return SC_STATUS_OK;
    case MACHINEFIRINGORDER_ACTION_A_COMPLETION_EFFECT:
        ctx->seq = ctx->seq + 1;
        ctx->effectAt = ctx->seq;
        return SC_STATUS_OK;
    default:
        return SC_STATUS_ERROR;
    }
}
