/*
 * sm07_machinefiringorder.c
 *
 * AUTO-GENERATED by sysmlc statix backend from state def 'SM07::MachineFiringOrder'. DO NOT EDIT.
 */

#include "sm07_machinefiringorder.h"

/* Static state and transition tables. */
static const sc_state_def_t sm07_machinefiringorder_states[] = {
    {SC_ACTION_NONE, SM07_MACHINEFIRINGORDER_ACTION_A_EXIT},
    {SM07_MACHINEFIRINGORDER_ACTION_B_ENTRY, SC_ACTION_NONE},
};

static const sc_transition_t sm07_machinefiringorder_transitions[] = {
    {SM07_MACHINEFIRINGORDER_STATE_A, SC_EVENT_COMPLETION, SC_GUARD_NONE, SM07_MACHINEFIRINGORDER_ACTION_A_COMPLETION_EFFECT, SM07_MACHINEFIRINGORDER_STATE_B},
};

static const sc_machine_t sm07_machinefiringorder_machine = {
    sm07_machinefiringorder_transitions,
    sm07_machinefiringorder_states,
    (uint16_t)(sizeof(sm07_machinefiringorder_transitions) / sizeof(sm07_machinefiringorder_transitions[0])),
    SM07_MACHINEFIRINGORDER_STATE_COUNT,
    SM07_MACHINEFIRINGORDER_STATE_A,
};

/* Generated guard/action dispatch. */
static bool sm07_machinefiringorder_guard_eval(sc_guard_id_t guard_id, const sc_runtime_t *runtime, const sc_event_t *event)
{
    (void)runtime;
    (void)event;
    (void)guard_id;
    return false;
}

static sc_status_t sm07_machinefiringorder_action_exec(sc_action_id_t action_id, sc_runtime_t *runtime, const sc_event_t *event)
{
    sm07_machinefiringorder_context_t *ctx = (sm07_machinefiringorder_context_t *)runtime->user_data;
    (void)event;
    if (ctx == NULL) { return SC_STATUS_INVALID_ARGUMENT; }
    switch (action_id) {
    case SM07_MACHINEFIRINGORDER_ACTION_A_EXIT:
        ctx->seq = ctx->seq + 1;
        ctx->exitAt = ctx->seq;
        return SC_STATUS_OK;
    case SM07_MACHINEFIRINGORDER_ACTION_B_ENTRY:
        ctx->seq = ctx->seq + 1;
        ctx->entryAt = ctx->seq;
        return SC_STATUS_OK;
    case SM07_MACHINEFIRINGORDER_ACTION_A_COMPLETION_EFFECT:
        ctx->seq = ctx->seq + 1;
        ctx->effectAt = ctx->seq;
        return SC_STATUS_OK;
    default:
        return SC_STATUS_ERROR;
    }
}

/* Private dispatch helpers. */
static sc_status_t sm07_machinefiringorder_run_state_action(sm07_machinefiringorder_t *sm, sc_action_id_t action, const sc_event_t *event)
{
    if (action == SC_ACTION_NONE) {
        return SC_STATUS_OK;
    }
    return sm07_machinefiringorder_action_exec(action, &sm->runtime, event);
}

static int32_t sm07_machinefiringorder_find_transition(const sc_machine_t *machine, sc_state_id_t state, sc_event_id_t event_id, const sm07_machinefiringorder_t *sm, const sc_event_t *event)
{
    uint16_t limit = machine->transition_count;
    uint16_t i;
    if (limit > (uint16_t)SC_MAX_TRANSITIONS) {
        limit = (uint16_t)SC_MAX_TRANSITIONS;
    }
    for (i = 0u; i < limit; ++i) {
        const sc_transition_t *t = &machine->transitions[i];
        if ((t->source == state) && (t->event == event_id)) {
            bool enabled = (t->guard == SC_GUARD_NONE) ? true : sm07_machinefiringorder_guard_eval(t->guard, &sm->runtime, event);
            if (enabled) {
                return (int32_t)i;
            }
        }
    }
    return -1;
}

static sc_status_t sm07_machinefiringorder_take_transition(sm07_machinefiringorder_t *sm, const sc_transition_t *t, const sc_event_t *event)
{
    const sc_machine_t *machine = sm->runtime.machine;
    sc_status_t status;

    status = sm07_machinefiringorder_run_state_action(sm, machine->states[sm->runtime.current_state].exit_action, event);
    if (status != SC_STATUS_OK) {
        return status;
    }
    if (t->action != SC_ACTION_NONE) {
        status = sm07_machinefiringorder_action_exec(t->action, &sm->runtime, event);
        if (status != SC_STATUS_OK) {
            return status;
        }
    }
    sm->runtime.current_state = t->target;
    return sm07_machinefiringorder_run_state_action(sm, machine->states[t->target].entry_action, event);
}

static sc_status_t sm07_machinefiringorder_run_completion(sm07_machinefiringorder_t *sm)
{
    const sc_machine_t *machine = sm->runtime.machine;
    sc_event_t completion;
    uint16_t step;
    (void)sc_event_init(&completion, SC_EVENT_COMPLETION);
    for (step = 0u; step < (uint16_t)SC_MAX_RTC_STEPS; ++step) {
        int32_t idx = sm07_machinefiringorder_find_transition(machine, sm->runtime.current_state, SC_EVENT_COMPLETION, sm, &completion);
        sc_status_t status;
        if (idx < 0) {
            return SC_STATUS_OK;
        }
        status = sm07_machinefiringorder_take_transition(sm, &machine->transitions[idx], &completion);
        if (status != SC_STATUS_OK) {
            return status;
        }
    }
    return SC_STATUS_STEP_LIMIT;
}

/* Public API. */
void sm07_machinefiringorder_context_init(sm07_machinefiringorder_context_t *ctx)
{
    if (ctx == NULL) {
        return;
    }
    *ctx = (sm07_machinefiringorder_context_t){.seq = 0, .exitAt = 0, .effectAt = 0, .entryAt = 0};
}

sc_status_t sm07_machinefiringorder_init(sm07_machinefiringorder_t *sm, sm07_machinefiringorder_context_t *ctx)
{
    sc_status_t status;
    sc_event_t completion;
    if ((sm == NULL) || (ctx == NULL)) {
        return SC_STATUS_INVALID_ARGUMENT;
    }
    status = sc_runtime_bind(&sm->runtime, &sm07_machinefiringorder_machine, ctx);
    if (status != SC_STATUS_OK) {
        return status;
    }
    (void)sc_event_init(&completion, SC_EVENT_COMPLETION);
    status = sm07_machinefiringorder_run_state_action(sm, sm07_machinefiringorder_machine.states[sm07_machinefiringorder_machine.initial_state].entry_action, &completion);
    if (status != SC_STATUS_OK) {
        return status;
    }
    return sm07_machinefiringorder_run_completion(sm);
}

sc_status_t sm07_machinefiringorder_dispatch(sm07_machinefiringorder_t *sm, const sc_event_t *event)
{
    const sc_machine_t *machine;
    int32_t idx;
    sc_status_t status;
    if ((sm == NULL) || (event == NULL) || (!sm->runtime.initialized)) {
        return SC_STATUS_INVALID_ARGUMENT;
    }
    machine = sm->runtime.machine;
    if ((machine == NULL) || (machine->transitions == NULL) || (machine->states == NULL)) {
        return SC_STATUS_INVALID_ARGUMENT;
    }
    idx = sm07_machinefiringorder_find_transition(machine, sm->runtime.current_state, event->id, sm, event);
    if (idx < 0) {
        return SC_STATUS_NO_TRANSITION;
    }
    status = sm07_machinefiringorder_take_transition(sm, &machine->transitions[idx], event);
    if (status != SC_STATUS_OK) {
        return status;
    }
    return sm07_machinefiringorder_run_completion(sm);
}

sc_status_t sm07_machinefiringorder_post(sm07_machinefiringorder_t *sm, sc_event_id_t event_id)
{
    sc_event_t event;
    sc_status_t status = sc_event_init(&event, event_id);
    if (status != SC_STATUS_OK) {
        return status;
    }
    return sm07_machinefiringorder_dispatch(sm, &event);
}

sc_state_id_t sm07_machinefiringorder_get_state(const sm07_machinefiringorder_t *sm)
{
    sc_state_id_t state = SC_STATE_INVALID;
    if (sm == NULL) {
        return SC_STATE_INVALID;
    }
    (void)sc_runtime_get_state(&sm->runtime, &state);
    return state;
}

const char *sm07_machinefiringorder_state_name(sc_state_id_t state)
{
    switch (state) {
    case SM07_MACHINEFIRINGORDER_STATE_A:
        return "a";
    case SM07_MACHINEFIRINGORDER_STATE_B:
        return "b";
    case SC_STATE_INVALID:
        return "SC_STATE_INVALID";
    default:
        return "SC_STATE_UNKNOWN";
    }
}

const char *sm07_machinefiringorder_event_name(sc_event_id_t event)
{
    switch (event) {
    case SC_EVENT_COMPLETION:
        return "SC_EVENT_COMPLETION";
    case SC_EVENT_INVALID:
        return "SC_EVENT_INVALID";
    default:
        return "SC_EVENT_UNKNOWN";
    }
}
