/*
 * sm07_machinefiringorder.c
 *
 * AUTO-GENERATED by sysmlc statix backend from state def 'SM07::MachineFiringOrder'. DO NOT EDIT.
 */

#include "sm07_machinefiringorder.h"

/* Static state and transition tables. */
static const sc_state_def_t sm07_machinefiringorder_states[] = {
    {SC_ACTION_NONE, SM07_MACHINEFIRINGORDER_ACTION_A_EXIT},
    {SM07_MACHINEFIRINGORDER_ACTION_B_ENTRY, SC_ACTION_NONE},
};

static const sc_transition_t sm07_machinefiringorder_transitions[] = {
    {SM07_MACHINEFIRINGORDER_STATE_A, SC_EVENT_COMPLETION, SC_GUARD_NONE, SM07_MACHINEFIRINGORDER_ACTION_A_COMPLETION_EFFECT, SM07_MACHINEFIRINGORDER_STATE_B},
};

static const sc_machine_t sm07_machinefiringorder_machine = {
    sm07_machinefiringorder_transitions,
    sm07_machinefiringorder_states,
    (uint16_t)(sizeof(sm07_machinefiringorder_transitions) / sizeof(sm07_machinefiringorder_transitions[0])),
    SM07_MACHINEFIRINGORDER_STATE_COUNT,
    SM07_MACHINEFIRINGORDER_STATE_A,
};

/* Generated guard/action dispatch. */
static bool sm07_machinefiringorder_guard_eval(sc_guard_id_t guard_id, const sc_runtime_t *runtime, const sc_event_t *event)
{
    (void)runtime;
    (void)event;
    (void)guard_id;
    return false;
}

static sc_status_t sm07_machinefiringorder_action_exec(sc_action_id_t action_id, sc_runtime_t *runtime, const sc_event_t *event)
{
    sm07_machinefiringorder_context_t *ctx = (sm07_machinefiringorder_context_t *)runtime->user_data;
    (void)event;
    if (ctx == NULL) { return SC_STATUS_INVALID_ARGUMENT; }
    switch (action_id) {
    case SM07_MACHINEFIRINGORDER_ACTION_A_EXIT:
        ctx->seq = ctx->seq + 1;
        ctx->exitAt = ctx->seq;
        return SC_STATUS_OK;
    case SM07_MACHINEFIRINGORDER_ACTION_B_ENTRY:
        ctx->seq = ctx->seq + 1;
        ctx->entryAt = ctx->seq;
        return SC_STATUS_OK;
    case SM07_MACHINEFIRINGORDER_ACTION_A_COMPLETION_EFFECT:
        ctx->seq = ctx->seq + 1;
        ctx->effectAt = ctx->seq;
        return SC_STATUS_OK;
    default:
        return SC_STATUS_ERROR;
    }
}

void sm07_machinefiringorder_context_init(sm07_machinefiringorder_context_t *ctx)
{
    if (ctx == NULL) {
        return;
    }
    *ctx = (sm07_machinefiringorder_context_t){.seq = 0, .exitAt = 0, .effectAt = 0, .entryAt = 0};
}

const char *sm07_machinefiringorder_state_name(sc_state_id_t state)
{
    switch (state) {
    case SM07_MACHINEFIRINGORDER_STATE_A:
        return "a";
    case SM07_MACHINEFIRINGORDER_STATE_B:
        return "b";
    case SC_STATE_INVALID:
        return "SC_STATE_INVALID";
    default:
        return "SC_STATE_UNKNOWN";
    }
}

const char *sm07_machinefiringorder_event_name(sc_event_id_t event)
{
    switch (event) {
    case SC_EVENT_COMPLETION:
        return "SC_EVENT_COMPLETION";
    case SC_EVENT_INVALID:
        return "SC_EVENT_INVALID";
    default:
        return "SC_EVENT_UNKNOWN";
    }
}

/* Instantiate the shared dispatch for this machine. */
#define SC_MACHINE_PREFIX sm07_machinefiringorder
#define SC_MACHINE_DEF sm07_machinefiringorder_machine
#define SC_MACHINE_GUARD sm07_machinefiringorder_guard_eval
#define SC_MACHINE_ACTION sm07_machinefiringorder_action_exec
#include "sc/sc_machine.h"
