#ifndef MACHINEFIRINGORDER_CONTEXT_H
#define MACHINEFIRINGORDER_CONTEXT_H

/*
 * machinefiringorder_context.h
 *
 * AUTO-GENERATED by sysmlc statix backend from state def 'MachineFiringOrder'. DO NOT EDIT.
 */

#include "sc/sc_types.h"

typedef struct machinefiringorder_context_s {
    int32_t seq;
    int32_t exitAt;
    int32_t effectAt;
    int32_t entryAt;
} machinefiringorder_context_t;

#endif /* MACHINEFIRINGORDER_CONTEXT_H */
