/*
 * sm07/machine_firing_order_runner.c
 *
 * AUTO-GENERATED by sysmlc statix backend from state def 'SM07::MachineFiringOrder'. DO NOT EDIT.
 */

#include "sm07/machine_firing_order.h"

#include <stdio.h>
#include <string.h>

static bool sm07_machine_firing_order_event_from_name(const char *name, sc_event_id_t *event_id)
{
    if ((name == NULL) || (event_id == NULL)) {
        return false;
    }
    return false;
}

static void sm07_machine_firing_order_print_configuration(const sm07_machine_firing_order_t *sm)
{
    sc_state_id_t count = sm07_machine_firing_order_active_count(sm);
    sc_state_id_t i;
    (void)printf(" configuration=");
    for (i = 0; i < count; ++i) {
        if (i > 0) {
            (void)printf(",");
        }
        (void)printf("%s", sm07_machine_firing_order_state_name(sm07_machine_firing_order_active_state(sm, i)));
    }
}

static void sm07_machine_firing_order_print_help(const char *argv0)
{
    (void)printf("Usage: %s [-h|--help]", argv0);
    (void)printf(" [EVENT ...]\n\n");

    (void)printf("Machine: SM07::MachineFiringOrder\n");
    (void)printf("Initial state: a\n\n");

    (void)printf("States:\n");
    (void)printf("  a (initial)\n");
    (void)printf("  b\n");
    (void)printf("\n");

    (void)printf("Events:\n");
    (void)printf("  (none -- this machine accepts no external events)\n");
    (void)printf("\n");

    (void)printf("Transitions (source -> event -> target, guard, action):\n");
    (void)printf("  a -[(completion)]-> b  guard=- action=a_completion_effect\n");
    (void)printf("\n");



    (void)printf("Example:\n  %s\n  (this machine has no external events; running with no\n", argv0);
    (void)printf("  arguments alone initializes it to its settled starting configuration)\n\n");

    (void)printf("Tracing: enabled by default (all kinds). Disable at compile time with\n");
    (void)printf("  -DSM07_MACHINE_FIRING_ORDER_TRACE_MASK=0, or select specific kinds by OR-ing\n");
    (void)printf("  SC_TRACE_MASK_ENTER/_EXIT/_TRANSITION/_GUARD/_TIMER_CHECK.\n");
}

int main(int argc, char **argv)
{
    sm07_machine_firing_order_context_t ctx;
    sm07_machine_firing_order_t sm;
    sc_status_t status;
    int i;

    for (i = 1; i < argc; ++i) {
        if ((strcmp(argv[i], "-h") == 0) || (strcmp(argv[i], "--help") == 0)) {
            sm07_machine_firing_order_print_help(argv[0]);
            return 0;
        }
    }

    sm07_machine_firing_order_context_init(&ctx);
    status = sm07_machine_firing_order_init(&sm, &ctx);
    (void)printf("init status=%s state=%s final=%d ctx.seq=%d ctx.exitAt=%d ctx.effectAt=%d ctx.entryAt=%d", sc_status_str(status),
                 sm07_machine_firing_order_state_name(sm07_machine_firing_order_get_state(&sm)), (int)sm07_machine_firing_order_is_final(&sm), ctx.seq, ctx.exitAt, ctx.effectAt, ctx.entryAt);
    sm07_machine_firing_order_print_configuration(&sm);
    (void)printf("\n");
    if (status != SC_STATUS_OK) {
        return 1;
    }

    for (i = 1; i < argc; ++i) {
        sc_event_id_t event_id = SC_EVENT_INVALID;
        /* Exact-or-"=" boundary match (not a bare strncmp prefix check) so
         * --tickfoo" falls through to the generic unknown-option path below
         * instead of being misreported as the unsupported --tick option. */
        if ((strcmp(argv[i], "--tick") == 0) || (strncmp(argv[i], "--tick=", 7) == 0) ||
            (strcmp(argv[i], "--advance") == 0) || (strncmp(argv[i], "--advance=", 10) == 0)) {
            const char *opt = (strncmp(argv[i], "--tick", 6) == 0) ? "--tick" : "--advance";
            (void)fprintf(stderr, "error: option '%s' is not supported by this machine\n", opt);
            (void)fprintf(stderr, "Try '%s --help' for usage.\n", argv[0]);
            return 2;
        }
        if ((argv[i][0] == '-') && !sm07_machine_firing_order_event_from_name(argv[i], &event_id)) {
            (void)fprintf(stderr, "error: unknown option: %s\n", argv[i]);
            (void)fprintf(stderr, "Try '%s --help' for usage.\n", argv[0]);
            return 2;
        }
        if (!sm07_machine_firing_order_event_from_name(argv[i], &event_id)) {
            (void)fprintf(stderr, "unknown event: %s\n", argv[i]);
            (void)fprintf(stderr, "Try '%s --help' for usage.\n", argv[0]);
            return 2;
        }
        status = sm07_machine_firing_order_post(&sm, event_id);
        (void)printf("event %s status=%s state=%s final=%d ctx.seq=%d ctx.exitAt=%d ctx.effectAt=%d ctx.entryAt=%d", argv[i],
                     sc_status_str(status), sm07_machine_firing_order_state_name(sm07_machine_firing_order_get_state(&sm)), (int)sm07_machine_firing_order_is_final(&sm), ctx.seq, ctx.exitAt, ctx.effectAt, ctx.entryAt);
        sm07_machine_firing_order_print_configuration(&sm);
        (void)printf("\n");
        if ((status != SC_STATUS_OK) && (status != SC_STATUS_NO_TRANSITION)) {
            return 1;
        }
    }
    return 0;
}
