/*
 * sm07/machine_firing_order_runner.c
 *
 * AUTO-GENERATED by sysmlc statix backend from state def 'SM07::MachineFiringOrder'. DO NOT EDIT.
 */

#include "sm07/machine_firing_order.h"

#include <stdio.h>
#include <string.h>

static bool sm07_machine_firing_order_event_from_name(const char *name, sc_event_id_t *event_id)
{
    if ((name == NULL) || (event_id == NULL)) {
        return false;
    }
    return false;
}

int main(int argc, char **argv)
{
    sm07_machine_firing_order_context_t ctx;
    sm07_machine_firing_order_t sm;
    sc_status_t status;
    int i;

    sm07_machine_firing_order_context_init(&ctx);
    status = sm07_machine_firing_order_init(&sm, &ctx);
    (void)printf("init status=%s state=%s final=%d\n", sc_status_str(status),
                 sm07_machine_firing_order_state_name(sm07_machine_firing_order_get_state(&sm)), (int)sm07_machine_firing_order_is_final(&sm));
    if (status != SC_STATUS_OK) {
        return 1;
    }

    for (i = 1; i < argc; ++i) {
        sc_event_id_t event_id = SC_EVENT_INVALID;
        if (!sm07_machine_firing_order_event_from_name(argv[i], &event_id)) {
            (void)fprintf(stderr, "unknown event: %s\n", argv[i]);
            return 2;
        }
        status = sm07_machine_firing_order_post(&sm, event_id);
        (void)printf("event %s status=%s state=%s final=%d\n", argv[i],
                     sc_status_str(status), sm07_machine_firing_order_state_name(sm07_machine_firing_order_get_state(&sm)), (int)sm07_machine_firing_order_is_final(&sm));
        if ((status != SC_STATUS_OK) && (status != SC_STATUS_NO_TRANSITION)) {
            return 1;
        }
    }
    return 0;
}
