#ifndef MACHINEFIRINGORDER_STATECHART_IDS_H
#define MACHINEFIRINGORDER_STATECHART_IDS_H

/*
 * machinefiringorder_statechart_ids.h
 *
 * AUTO-GENERATED by sysmlc statix backend from state def 'MachineFiringOrder'. DO NOT EDIT.
 */

/* States */
typedef enum machinefiringorder_state_e {
    MACHINEFIRINGORDER_STATE_A = 0,
    MACHINEFIRINGORDER_STATE_B = 1
} machinefiringorder_state_t;

#define MACHINEFIRINGORDER_STATE_COUNT 2u

/* Events */
/* (none defined in this model) */

/* Guards */
/* (none defined in this model) */

/* Actions */
typedef enum machinefiringorder_action_e {
    MACHINEFIRINGORDER_ACTION_A_EXIT = 1,
    MACHINEFIRINGORDER_ACTION_B_ENTRY = 2,
    MACHINEFIRINGORDER_ACTION_A_COMPLETION_EFFECT = 3
} machinefiringorder_action_t;

#endif /* MACHINEFIRINGORDER_STATECHART_IDS_H */
