#ifndef SM07_MACHINE_FIRING_ORDER_H
#define SM07_MACHINE_FIRING_ORDER_H

/*
 * sm07/machine_firing_order.h
 *
 * AUTO-GENERATED by sysmlc statix backend from state def 'SM07::MachineFiringOrder'. DO NOT EDIT.
 */

#include "sc/sc_runtime.h"

#ifdef __cplusplus
extern "C" {
#endif

/// @brief Generated state identifiers.
typedef enum sm07_machine_firing_order_state_e {
    SM07_MACHINE_FIRING_ORDER_STATE_A = 0, ///< @brief State 'a'.
    SM07_MACHINE_FIRING_ORDER_STATE_B = 1 ///< @brief State 'b'.
} sm07_machine_firing_order_state_t;

#define SM07_MACHINE_FIRING_ORDER_STATE_COUNT 2u

/// @brief Generated signal event identifiers.
/* (none defined in this model) */

/// @brief Generated guard identifiers.
/* (none defined in this model) */

/// @brief Generated action identifiers.
typedef enum sm07_machine_firing_order_action_e {
    SM07_MACHINE_FIRING_ORDER_ACTION_A_EXIT = 1, ///< @brief Generated action 'a_exit'.
    SM07_MACHINE_FIRING_ORDER_ACTION_B_ENTRY = 2, ///< @brief Generated action 'b_entry'.
    SM07_MACHINE_FIRING_ORDER_ACTION_A_COMPLETION_EFFECT = 3 ///< @brief Generated action 'a_completion_effect'.
} sm07_machine_firing_order_action_t;


#define SM07_MACHINE_FIRING_ORDER_QUEUE_CAPACITY 8u
#define SM07_MACHINE_FIRING_ORDER_ACTIVE_CAPACITY 1u

/// @brief Generated context for SM07::MachineFiringOrder.
typedef struct sm07_machine_firing_order_context_s {
    int32_t seq;
    int32_t exitAt;
    int32_t effectAt;
    int32_t entryAt;
} sm07_machine_firing_order_context_t;

/// @brief Runtime instance for SM07::MachineFiringOrder.
typedef struct sm07_machine_firing_order_s {
    sc_runtime_t runtime;
    sc_activation_t active[SM07_MACHINE_FIRING_ORDER_ACTIVE_CAPACITY];
} sm07_machine_firing_order_t;

/// @brief Initialize a generated context object with model default values.
/// @param ctx Context object to initialize.
void sm07_machine_firing_order_context_init(sm07_machine_firing_order_context_t *ctx);

/// @brief Initialize a statechart instance and enter its initial state.
/// @param sm Statechart instance to initialize.
/// @param ctx Context object owned by the caller.
/// @return SC_STATUS_OK on success, or an error status.
sc_status_t sm07_machine_firing_order_init(sm07_machine_firing_order_t *sm, sm07_machine_firing_order_context_t *ctx);

/// @brief Dispatch one event into the statechart.
/// @param sm Statechart instance receiving the event.
/// @param event Event to dispatch.
/// @return SC_STATUS_OK if a transition fired, SC_STATUS_NO_TRANSITION if none matched, or an error status.
sc_status_t sm07_machine_firing_order_dispatch(sm07_machine_firing_order_t *sm, const sc_event_t *event);

/// @brief Dispatch one no-payload event by id.
/// @param sm Statechart instance receiving the event.
/// @param event_id Event identifier to dispatch.
/// @return SC_STATUS_OK if a transition fired, SC_STATUS_NO_TRANSITION if none matched, or an error status.
sc_status_t sm07_machine_firing_order_post(sm07_machine_firing_order_t *sm, sc_event_id_t event_id);

/// @brief Return the currently active state.
/// @param sm Statechart instance to inspect.
/// @return Active state id, or SC_STATE_INVALID before initialization.
sc_state_id_t sm07_machine_firing_order_get_state(const sm07_machine_firing_order_t *sm);

/// @brief Whether the machine reached a root-level final state (terminated).
/// @param sm Statechart instance to inspect.
/// @return true if the active leaf is a root-scope final state.
bool sm07_machine_firing_order_is_final(const sm07_machine_firing_order_t *sm);

/// @brief Number of currently active true leaves.
/// @param sm Statechart instance to inspect.
/// @return Count of active true leaves, or 0 before initialization.
sc_state_id_t sm07_machine_firing_order_active_count(const sm07_machine_firing_order_t *sm);

/// @brief The k-th currently active true leaf, in ascending slot order.
/// @param sm Statechart instance to inspect.
/// @param index Which active leaf to return, 0 <= index < sm07_machine_firing_order_active_count(sm).
/// @return The index-th active leaf, or SC_STATE_INVALID if out of range.
sc_state_id_t sm07_machine_firing_order_active_state(const sm07_machine_firing_order_t *sm, sc_state_id_t index);

/// @brief Return a stable name for a generated state id.
/// @param state State identifier to name.
/// @return Static non-NULL state name.
const char *sm07_machine_firing_order_state_name(sc_state_id_t state);

/// @brief Return a stable name for a generated event id.
/// @param event Event identifier to name.
/// @return Static non-NULL event name.
const char *sm07_machine_firing_order_event_name(sc_event_id_t event);

#ifdef __cplusplus
}
#endif

#endif /* SM07_MACHINE_FIRING_ORDER_H */
