/*
 * machinefiringorder_statechart_config.c
 *
 * AUTO-GENERATED by sysmlc statix backend from state def 'MachineFiringOrder'. DO NOT EDIT.
 */

#include "machinefiringorder_statechart_config.h"

/* Per-state entry/exit action table (indexed by state id). */
static const sc_state_def_t machinefiringorder_states[] = {
    {SC_ACTION_NONE, MACHINEFIRINGORDER_ACTION_A_EXIT},
    {MACHINEFIRINGORDER_ACTION_B_ENTRY, SC_ACTION_NONE},
};

/* Transition rows: {source, event, guard, action, target}. */
static const sc_transition_t machinefiringorder_transitions[] = {
    {MACHINEFIRINGORDER_STATE_A, SC_EVENT_COMPLETION, SC_GUARD_NONE, MACHINEFIRINGORDER_ACTION_A_COMPLETION_EFFECT, MACHINEFIRINGORDER_STATE_B},
};

const sc_machine_t machinefiringorder_statechart_machine = {
    machinefiringorder_transitions,
    machinefiringorder_states,
    (uint16_t)(sizeof(machinefiringorder_transitions) / sizeof(machinefiringorder_transitions[0])),
    MACHINEFIRINGORDER_STATE_COUNT,
    MACHINEFIRINGORDER_STATE_A,
};
