/*
 * sm04_machineentryincrement.c
 *
 * AUTO-GENERATED by sysmlc statix backend from state def 'SM04::MachineEntryIncrement'. DO NOT EDIT.
 */

#include "sm04_machineentryincrement.h"

/* Static state and transition tables. */
static const sc_state_def_t sm04_machineentryincrement_states[] = {
    {SM04_MACHINEENTRYINCREMENT_ACTION_IDLE_ENTRY, SC_ACTION_NONE},
    {SC_ACTION_NONE, SC_ACTION_NONE},
};

static const sc_transition_t sm04_machineentryincrement_transitions[] = {
    {SM04_MACHINEENTRYINCREMENT_STATE_IDLE, SC_EVENT_COMPLETION, SC_GUARD_NONE, SC_ACTION_NONE, SM04_MACHINEENTRYINCREMENT_STATE_RUNNING},
};

static const sc_machine_t sm04_machineentryincrement_machine = {
    sm04_machineentryincrement_transitions,
    sm04_machineentryincrement_states,
    (uint16_t)(sizeof(sm04_machineentryincrement_transitions) / sizeof(sm04_machineentryincrement_transitions[0])),
    SM04_MACHINEENTRYINCREMENT_STATE_COUNT,
    SM04_MACHINEENTRYINCREMENT_STATE_IDLE,
};

/* Generated guard/action dispatch. */
static bool sm04_machineentryincrement_guard_eval(sc_guard_id_t guard_id, const sc_runtime_t *runtime, const sc_event_t *event)
{
    (void)runtime;
    (void)event;
    (void)guard_id;
    return false;
}

static sc_status_t sm04_machineentryincrement_action_exec(sc_action_id_t action_id, sc_runtime_t *runtime, const sc_event_t *event)
{
    sm04_machineentryincrement_context_t *ctx = (sm04_machineentryincrement_context_t *)runtime->user_data;
    (void)event;
    if (ctx == NULL) { return SC_STATUS_INVALID_ARGUMENT; }
    switch (action_id) {
    case SM04_MACHINEENTRYINCREMENT_ACTION_IDLE_ENTRY:
        ctx->counter = ctx->counter + 1;
        return SC_STATUS_OK;
    default:
        return SC_STATUS_ERROR;
    }
}

void sm04_machineentryincrement_context_init(sm04_machineentryincrement_context_t *ctx)
{
    if (ctx == NULL) {
        return;
    }
    *ctx = (sm04_machineentryincrement_context_t){.counter = 0};
}

const char *sm04_machineentryincrement_state_name(sc_state_id_t state)
{
    switch (state) {
    case SM04_MACHINEENTRYINCREMENT_STATE_IDLE:
        return "idle";
    case SM04_MACHINEENTRYINCREMENT_STATE_RUNNING:
        return "running";
    case SC_STATE_INVALID:
        return "SC_STATE_INVALID";
    default:
        return "SC_STATE_UNKNOWN";
    }
}

const char *sm04_machineentryincrement_event_name(sc_event_id_t event)
{
    switch (event) {
    case SC_EVENT_COMPLETION:
        return "SC_EVENT_COMPLETION";
    case SC_EVENT_INVALID:
        return "SC_EVENT_INVALID";
    default:
        return "SC_EVENT_UNKNOWN";
    }
}

/* Instantiate the shared dispatch for this machine. */
#define SC_MACHINE_PREFIX sm04_machineentryincrement
#define SC_MACHINE_DEF sm04_machineentryincrement_machine
#define SC_MACHINE_GUARD sm04_machineentryincrement_guard_eval
#define SC_MACHINE_ACTION sm04_machineentryincrement_action_exec
#include "sc/sc_machine.h"
