/*
 * machineentryincrement_actions.c
 *
 * AUTO-GENERATED by sysmlc statix backend from state def 'MachineEntryIncrement'. DO NOT EDIT.
 */

#include "machineentryincrement_statechart_ids.h"
#include "machineentryincrement_context.h"
#include "sc/sc_runtime.h"

bool sc_guard_eval(sc_guard_id_t guard_id, const sc_runtime_t *runtime, const sc_event_t *event)
{
    (void)runtime;
    (void)event;
    (void)guard_id;
    return false;
}

sc_status_t sc_action_exec(sc_action_id_t action_id, sc_runtime_t *runtime, const sc_event_t *event)
{
    machineentryincrement_context_t *ctx = (machineentryincrement_context_t *)runtime->user_data;
    (void)event;
    if (ctx == NULL) { return SC_STATUS_INVALID_ARGUMENT; }
    switch (action_id) {
    case MACHINEENTRYINCREMENT_ACTION_IDLE_ENTRY:
        ctx->counter = ctx->counter + 1;
        return SC_STATUS_OK;
    default:
        return SC_STATUS_ERROR;
    }
}
