/*
 * machineentryincrement_statechart_config.c
 *
 * AUTO-GENERATED by sysmlc statix backend from state def 'MachineEntryIncrement'. DO NOT EDIT.
 */

#include "machineentryincrement_statechart_config.h"

/* Per-state entry/exit action table (indexed by state id). */
static const sc_state_def_t machineentryincrement_states[] = {
    {MACHINEENTRYINCREMENT_ACTION_IDLE_ENTRY, SC_ACTION_NONE},
    {SC_ACTION_NONE, SC_ACTION_NONE},
};

/* Transition rows: {source, event, guard, action, target}. */
static const sc_transition_t machineentryincrement_transitions[] = {
    {MACHINEENTRYINCREMENT_STATE_IDLE, SC_EVENT_COMPLETION, SC_GUARD_NONE, SC_ACTION_NONE, MACHINEENTRYINCREMENT_STATE_RUNNING},
};

const sc_machine_t machineentryincrement_statechart_machine = {
    machineentryincrement_transitions,
    machineentryincrement_states,
    (uint16_t)(sizeof(machineentryincrement_transitions) / sizeof(machineentryincrement_transitions[0])),
    MACHINEENTRYINCREMENT_STATE_COUNT,
    MACHINEENTRYINCREMENT_STATE_IDLE,
};
