#ifndef MACHINEENTRYINCREMENT_STATECHART_IDS_H
#define MACHINEENTRYINCREMENT_STATECHART_IDS_H

/*
 * machineentryincrement_statechart_ids.h
 *
 * AUTO-GENERATED by sysmlc statix backend from state def 'MachineEntryIncrement'. DO NOT EDIT.
 */

/* States */
typedef enum machineentryincrement_state_e {
    MACHINEENTRYINCREMENT_STATE_IDLE = 0,
    MACHINEENTRYINCREMENT_STATE_RUNNING = 1
} machineentryincrement_state_t;

#define MACHINEENTRYINCREMENT_STATE_COUNT 2u

/* Events */
/* (none defined in this model) */

/* Guards */
/* (none defined in this model) */

/* Actions */
typedef enum machineentryincrement_action_e {
    MACHINEENTRYINCREMENT_ACTION_IDLE_ENTRY = 1
} machineentryincrement_action_t;

#endif /* MACHINEENTRYINCREMENT_STATECHART_IDS_H */
