#ifndef SM04_MACHINE_ENTRY_INCREMENT_H
#define SM04_MACHINE_ENTRY_INCREMENT_H

/*
 * sm04/machine_entry_increment.h
 *
 * AUTO-GENERATED by sysmlc statix backend from state def 'SM04::MachineEntryIncrement'. DO NOT EDIT.
 */

#include "sc/sc_runtime.h"

#ifdef __cplusplus
extern "C" {
#endif

/// @brief Generated state identifiers.
typedef enum sm04_machine_entry_increment_state_e {
    SM04_MACHINE_ENTRY_INCREMENT_STATE_IDLE = 0, ///< @brief State 'idle'.
    SM04_MACHINE_ENTRY_INCREMENT_STATE_RUNNING = 1 ///< @brief State 'running'.
} sm04_machine_entry_increment_state_t;

#define SM04_MACHINE_ENTRY_INCREMENT_STATE_COUNT 2u

/// @brief Generated signal event identifiers.
/* (none defined in this model) */

/// @brief Generated guard identifiers.
/* (none defined in this model) */

/// @brief Generated action identifiers.
typedef enum sm04_machine_entry_increment_action_e {
    SM04_MACHINE_ENTRY_INCREMENT_ACTION_IDLE_ENTRY = 1 ///< @brief Generated action 'idle_entry'.
} sm04_machine_entry_increment_action_t;


#define SM04_MACHINE_ENTRY_INCREMENT_QUEUE_CAPACITY 8u

/// @brief Generated context for SM04::MachineEntryIncrement.
typedef struct sm04_machine_entry_increment_context_s {
    int32_t counter;
} sm04_machine_entry_increment_context_t;

/// @brief Runtime instance for SM04::MachineEntryIncrement.
typedef struct sm04_machine_entry_increment_s {
    sc_runtime_t runtime;
} sm04_machine_entry_increment_t;

/// @brief Initialize a generated context object with model default values.
/// @param ctx Context object to initialize.
void sm04_machine_entry_increment_context_init(sm04_machine_entry_increment_context_t *ctx);

/// @brief Initialize a statechart instance and enter its initial state.
/// @param sm Statechart instance to initialize.
/// @param ctx Context object owned by the caller.
/// @return SC_STATUS_OK on success, or an error status.
sc_status_t sm04_machine_entry_increment_init(sm04_machine_entry_increment_t *sm, sm04_machine_entry_increment_context_t *ctx);

/// @brief Dispatch one event into the statechart.
/// @param sm Statechart instance receiving the event.
/// @param event Event to dispatch.
/// @return SC_STATUS_OK if a transition fired, SC_STATUS_NO_TRANSITION if none matched, or an error status.
sc_status_t sm04_machine_entry_increment_dispatch(sm04_machine_entry_increment_t *sm, const sc_event_t *event);

/// @brief Dispatch one no-payload event by id.
/// @param sm Statechart instance receiving the event.
/// @param event_id Event identifier to dispatch.
/// @return SC_STATUS_OK if a transition fired, SC_STATUS_NO_TRANSITION if none matched, or an error status.
sc_status_t sm04_machine_entry_increment_post(sm04_machine_entry_increment_t *sm, sc_event_id_t event_id);

/// @brief Return the currently active state.
/// @param sm Statechart instance to inspect.
/// @return Active state id, or SC_STATE_INVALID before initialization.
sc_state_id_t sm04_machine_entry_increment_get_state(const sm04_machine_entry_increment_t *sm);

/// @brief Whether the machine reached a root-level final state (terminated).
/// @param sm Statechart instance to inspect.
/// @return true if the active leaf is a root-scope final state.
bool sm04_machine_entry_increment_is_final(const sm04_machine_entry_increment_t *sm);

/// @brief Return a stable name for a generated state id.
/// @param state State identifier to name.
/// @return Static non-NULL state name.
const char *sm04_machine_entry_increment_state_name(sc_state_id_t state);

/// @brief Return a stable name for a generated event id.
/// @param event Event identifier to name.
/// @return Static non-NULL event name.
const char *sm04_machine_entry_increment_event_name(sc_event_id_t event);

#ifdef __cplusplus
}
#endif

#endif /* SM04_MACHINE_ENTRY_INCREMENT_H */
