#ifndef MACHINEENTRYINCREMENT_CONTEXT_H
#define MACHINEENTRYINCREMENT_CONTEXT_H

/*
 * machineentryincrement_context.h
 *
 * AUTO-GENERATED by sysmlc statix backend from state def 'MachineEntryIncrement'. DO NOT EDIT.
 */

#include "sc/sc_types.h"

typedef struct machineentryincrement_context_s {
    int32_t counter;
} machineentryincrement_context_t;

#endif /* MACHINEENTRYINCREMENT_CONTEXT_H */
