/*
 * sm04/machine_entry_increment_runner.c
 *
 * AUTO-GENERATED by sysmlc statix backend from state def 'SM04::MachineEntryIncrement'. DO NOT EDIT.
 */

#include "sm04/machine_entry_increment.h"

#include <stdio.h>
#include <string.h>

static bool sm04_machine_entry_increment_event_from_name(const char *name, sc_event_id_t *event_id)
{
    if ((name == NULL) || (event_id == NULL)) {
        return false;
    }
    return false;
}

int main(int argc, char **argv)
{
    sm04_machine_entry_increment_context_t ctx;
    sm04_machine_entry_increment_t sm;
    sc_status_t status;
    int i;

    sm04_machine_entry_increment_context_init(&ctx);
    status = sm04_machine_entry_increment_init(&sm, &ctx);
    (void)printf("init status=%s state=%s\n", sc_status_str(status),
                 sm04_machine_entry_increment_state_name(sm04_machine_entry_increment_get_state(&sm)));
    if (status != SC_STATUS_OK) {
        return 1;
    }

    for (i = 1; i < argc; ++i) {
        sc_event_id_t event_id = SC_EVENT_INVALID;
        if (!sm04_machine_entry_increment_event_from_name(argv[i], &event_id)) {
            (void)fprintf(stderr, "unknown event: %s\n", argv[i]);
            return 2;
        }
        status = sm04_machine_entry_increment_post(&sm, event_id);
        (void)printf("event %s status=%s state=%s\n", argv[i],
                     sc_status_str(status), sm04_machine_entry_increment_state_name(sm04_machine_entry_increment_get_state(&sm)));
        if ((status != SC_STATUS_OK) && (status != SC_STATUS_NO_TRANSITION)) {
            return 1;
        }
    }
    return 0;
}
