/*
 * sm11/machine_mixed.c
 *
 * AUTO-GENERATED by sysmlc statix backend from state def 'SM11::MachineMixed'. DO NOT EDIT.
 */

#include "sm11/machine_mixed.h"

/* Static state and transition tables (file-local). */
static const sc_state_def_t states[] = {
    {SC_ACTION_NONE, SC_ACTION_NONE, SC_STATE_INVALID, SC_STATE_INVALID, false},
    {SC_ACTION_NONE, SC_ACTION_NONE, SC_STATE_INVALID, SC_STATE_INVALID, false},
};

static const sc_transition_t transitions[] = {
    {SM11_MACHINE_MIXED_STATE_IDLE, SC_EVENT_COMPLETION, SC_GUARD_NONE, SM11_MACHINE_MIXED_ACTION_IDLE_COMPLETION_EFFECT, SM11_MACHINE_MIXED_STATE_ARMED},
};

static const sc_invariant_t invariants[] = {
    {SC_STATE_INVALID, SC_GUARD_NONE}
};

static const sc_machine_t machine_def = {
    transitions,
    states,
    (uint16_t)(sizeof(transitions) / sizeof(transitions[0])),
    SM11_MACHINE_MIXED_STATE_COUNT,
    SM11_MACHINE_MIXED_STATE_IDLE,
    (sc_state_id_t)1u,
    invariants,
    (uint16_t)0u,
};

/* Generated guard/action dispatch. */
static bool guard_eval(sc_guard_id_t guard_id, const sc_runtime_t *runtime, const sc_event_t *event)
{
    (void)runtime;
    (void)event;
    (void)guard_id;
    return false;
}

static sc_status_t action_exec(sc_action_id_t action_id, sc_runtime_t *runtime, const sc_event_t *event)
{
    sm11_machine_mixed_context_t *ctx = (sm11_machine_mixed_context_t *)runtime->user_data;
    (void)event;
    if (ctx == NULL) { return SC_STATUS_INVALID_ARGUMENT; }
    switch (action_id) {
    case SM11_MACHINE_MIXED_ACTION_IDLE_COMPLETION_EFFECT:
        ctx->count = ctx->count + 1;
        {
            sc_status_t send_status = sc_runtime_enqueue(
                runtime, (sc_event_id_t)SM11_MACHINE_MIXED_EVENT_PING);
            if (send_status != SC_STATUS_OK) {
                return send_status;
            }
        }
        return SC_STATUS_OK;
    default:
        return SC_STATUS_ERROR;
    }
}

void sm11_machine_mixed_context_init(sm11_machine_mixed_context_t *ctx)
{
    if (ctx == NULL) {
        return;
    }
    *ctx = (sm11_machine_mixed_context_t){.count = 0};
}

const char *sm11_machine_mixed_state_name(sc_state_id_t state)
{
    switch (state) {
    case SM11_MACHINE_MIXED_STATE_IDLE:
        return "idle";
    case SM11_MACHINE_MIXED_STATE_ARMED:
        return "armed";
    case SC_STATE_INVALID:
        return "SC_STATE_INVALID";
    default:
        return "SC_STATE_UNKNOWN";
    }
}

const char *sm11_machine_mixed_event_name(sc_event_id_t event)
{
    switch (event) {
    case SM11_MACHINE_MIXED_EVENT_PING:
        return "Ping";
    case SC_EVENT_COMPLETION:
        return "SC_EVENT_COMPLETION";
    case SC_EVENT_INVALID:
        return "SC_EVENT_INVALID";
    default:
        return "SC_EVENT_UNKNOWN";
    }
}

/* Instantiate the shared dispatch for this machine. */
#define SC_MACHINE_PREFIX sm11_machine_mixed
#define SC_MACHINE_DEF machine_def
#define SC_MACHINE_GUARD guard_eval
#define SC_MACHINE_ACTION action_exec
#define SC_MACHINE_HAS_QUEUE 1
#include "sc/sc_machine.h"
