#ifndef MACHINEEFFECT_STATECHART_IDS_H
#define MACHINEEFFECT_STATECHART_IDS_H

/*
 * machineeffect_statechart_ids.h
 *
 * AUTO-GENERATED by sysmlc statix backend from state def 'MachineEffect'. DO NOT EDIT.
 */

/* States */
typedef enum machineeffect_state_e {
    MACHINEEFFECT_STATE_IDLE = 0,
    MACHINEEFFECT_STATE_ARMED = 1,
    MACHINEEFFECT_STATE_RUNNING = 2
} machineeffect_state_t;

#define MACHINEEFFECT_STATE_COUNT 3u

/* Events */
/* (none defined in this model) */

/* Guards */
/* (none defined in this model) */

/* Actions */
typedef enum machineeffect_action_e {
    MACHINEEFFECT_ACTION_IDLE_COMPLETION_EFFECT = 1
} machineeffect_action_t;

#endif /* MACHINEEFFECT_STATECHART_IDS_H */
