/*
 * sm06/machine_effect_runner.c
 *
 * AUTO-GENERATED by sysmlc statix backend from state def 'SM06::MachineEffect'. DO NOT EDIT.
 */

#include "sm06/machine_effect.h"

#include <stdio.h>
#include <string.h>

static bool sm06_machine_effect_event_from_name(const char *name, sc_event_id_t *event_id)
{
    if ((name == NULL) || (event_id == NULL)) {
        return false;
    }
    return false;
}

static void sm06_machine_effect_print_configuration(const sm06_machine_effect_t *sm)
{
    sc_state_id_t count = sm06_machine_effect_active_count(sm);
    sc_state_id_t i;
    (void)printf(" configuration=");
    for (i = 0; i < count; ++i) {
        if (i > 0) {
            (void)printf(",");
        }
        (void)printf("%s", sm06_machine_effect_state_name(sm06_machine_effect_active_state(sm, i)));
    }
}

int main(int argc, char **argv)
{
    sm06_machine_effect_context_t ctx;
    sm06_machine_effect_t sm;
    sc_status_t status;
    int i;

    sm06_machine_effect_context_init(&ctx);
    status = sm06_machine_effect_init(&sm, &ctx);
    (void)printf("init status=%s state=%s final=%d ctx.counter=%d", sc_status_str(status),
                 sm06_machine_effect_state_name(sm06_machine_effect_get_state(&sm)), (int)sm06_machine_effect_is_final(&sm), ctx.counter);
    sm06_machine_effect_print_configuration(&sm);
    (void)printf("\n");
    if (status != SC_STATUS_OK) {
        return 1;
    }

    for (i = 1; i < argc; ++i) {
        sc_event_id_t event_id = SC_EVENT_INVALID;
        if (!sm06_machine_effect_event_from_name(argv[i], &event_id)) {
            (void)fprintf(stderr, "unknown event: %s\n", argv[i]);
            return 2;
        }
        status = sm06_machine_effect_post(&sm, event_id);
        (void)printf("event %s status=%s state=%s final=%d ctx.counter=%d", argv[i],
                     sc_status_str(status), sm06_machine_effect_state_name(sm06_machine_effect_get_state(&sm)), (int)sm06_machine_effect_is_final(&sm), ctx.counter);
        sm06_machine_effect_print_configuration(&sm);
        (void)printf("\n");
        if ((status != SC_STATUS_OK) && (status != SC_STATUS_NO_TRANSITION)) {
            return 1;
        }
    }
    return 0;
}
