#ifndef MACHINEEFFECT_CONTEXT_H
#define MACHINEEFFECT_CONTEXT_H

/*
 * machineeffect_context.h
 *
 * AUTO-GENERATED by sysmlc statix backend from state def 'MachineEffect'. DO NOT EDIT.
 */

#include "sc/sc_types.h"

typedef struct machineeffect_context_s {
    int32_t counter;
} machineeffect_context_t;

#endif /* MACHINEEFFECT_CONTEXT_H */
