/*
 * sm06/machine_effect.c
 *
 * AUTO-GENERATED by sysmlc statix backend from state def 'SM06::MachineEffect'. DO NOT EDIT.
 */

#include "sm06/machine_effect.h"

#ifndef SM06_MACHINE_EFFECT_TRACE_MASK
#define SM06_MACHINE_EFFECT_TRACE_MASK SC_TRACE_MASK_ALL
#endif
#if ((SM06_MACHINE_EFFECT_TRACE_MASK) & ~(SC_TRACE_MASK_ALL)) != 0u
#error "SM06_MACHINE_EFFECT_TRACE_MASK contains unsupported bits"
#endif
#define SM06_MACHINE_EFFECT_TRACE_AVAILABLE_MASK (SC_TRACE_MASK_ALL & ~SC_TRACE_MASK_TIMER_CHECK)
#define SC_MACHINE_TRACE_MASK \
    ((SM06_MACHINE_EFFECT_TRACE_MASK) & (SM06_MACHINE_EFFECT_TRACE_AVAILABLE_MASK))

#if SC_MACHINE_TRACE_MASK != 0u
#include <stdio.h>
#endif


/* Static state and transition tables (file-local). */
static const sc_state_def_t states[] = {
    {SC_ACTION_NONE, SC_ACTION_NONE, SC_STATE_INVALID, SC_STATE_INVALID, false, (sc_state_id_t)0u, SC_STATE_INVALID, (sc_state_id_t)0u},
    {SC_ACTION_NONE, SC_ACTION_NONE, SC_STATE_INVALID, SC_STATE_INVALID, false, (sc_state_id_t)0u, SC_STATE_INVALID, (sc_state_id_t)0u},
    {SC_ACTION_NONE, SC_ACTION_NONE, SC_STATE_INVALID, SC_STATE_INVALID, false, (sc_state_id_t)0u, SC_STATE_INVALID, (sc_state_id_t)0u},
};

static const sc_state_id_t regions[] = {
    SC_STATE_INVALID
};

static const sc_transition_t transitions[] = {
    {SM06_MACHINE_EFFECT_STATE_IDLE, SC_EVENT_COMPLETION, SC_GUARD_NONE, SM06_MACHINE_EFFECT_ACTION_IDLE_COMPLETION_EFFECT, SM06_MACHINE_EFFECT_STATE_ARMED},
    {SM06_MACHINE_EFFECT_STATE_ARMED, SC_EVENT_COMPLETION, SC_GUARD_NONE, SC_ACTION_NONE, SM06_MACHINE_EFFECT_STATE_RUNNING},
};

static const sc_invariant_t invariants[] = {
    {SC_STATE_INVALID, SC_GUARD_NONE}
};

static const sc_machine_t machine_def = {
    transitions,
    states,
    (uint16_t)(sizeof(transitions) / sizeof(transitions[0])),
    SM06_MACHINE_EFFECT_STATE_COUNT,
    SM06_MACHINE_EFFECT_STATE_IDLE,
    (sc_state_id_t)1u,
    invariants,
    (uint16_t)0u,
    regions,
    (sc_state_id_t)0u,
    (sc_state_id_t)SM06_MACHINE_EFFECT_ACTIVE_CAPACITY,
};

/* Generated guard/action dispatch. */
static bool guard_eval(sc_guard_id_t guard_id, const sc_runtime_t *runtime, const sc_event_t *event)
{
    (void)runtime;
    (void)event;
    (void)guard_id;
    return false;
}

static sc_status_t action_exec(sc_action_id_t action_id, sc_runtime_t *runtime, const sc_event_t *event)
{
    sm06_machine_effect_context_t *ctx = (sm06_machine_effect_context_t *)runtime->user_data;
    (void)event;
    if (ctx == NULL) { return SC_STATUS_INVALID_ARGUMENT; }
    switch (action_id) {
    case SM06_MACHINE_EFFECT_ACTION_IDLE_COMPLETION_EFFECT:
        ctx->counter = ctx->counter + 1;
        return SC_STATUS_OK;
    default:
        return SC_STATUS_ERROR;
    }
}

void sm06_machine_effect_context_init(sm06_machine_effect_context_t *ctx)
{
    if (ctx == NULL) {
        return;
    }
    *ctx = (sm06_machine_effect_context_t){.counter = 0};
}

const char *sm06_machine_effect_state_name(sc_state_id_t state)
{
    switch (state) {
    case SM06_MACHINE_EFFECT_STATE_IDLE:
        return "idle";
    case SM06_MACHINE_EFFECT_STATE_ARMED:
        return "armed";
    case SM06_MACHINE_EFFECT_STATE_RUNNING:
        return "running";
    case SC_STATE_INVALID:
        return "SC_STATE_INVALID";
    default:
        return "SC_STATE_UNKNOWN";
    }
}

const char *sm06_machine_effect_event_name(sc_event_id_t event)
{
    switch (event) {
    case SC_EVENT_COMPLETION:
        return "SC_EVENT_COMPLETION";
    case SC_EVENT_INVALID:
        return "SC_EVENT_INVALID";
    default:
        return "SC_EVENT_UNKNOWN";
    }
}

#if (SC_MACHINE_TRACE_MASK & SC_TRACE_MASK_GUARD)
static const char *guard_name(sc_guard_id_t guard)
{
    switch (guard) {
    default:
        return "SC_GUARD_UNKNOWN";
    }
}
#endif

#if (SC_MACHINE_TRACE_MASK & SC_TRACE_MASK_TRANSITION)
static const char *action_name(sc_action_id_t action)
{
    switch (action) {
    case SC_ACTION_NONE:
        return "SC_ACTION_NONE";
    case SM06_MACHINE_EFFECT_ACTION_IDLE_COMPLETION_EFFECT:
        return "idle_completion_effect";
    default:
        return "SC_ACTION_UNKNOWN";
    }
}
#endif

#if SC_MACHINE_TRACE_MASK != 0u
static void trace_hook(sc_trace_kind_t kind, const sc_runtime_t *runtime,
                        const sc_event_t *event, const sc_trace_data_t *data)
{
    (void)runtime;
    (void)event;
    switch (kind) {
#if (SC_MACHINE_TRACE_MASK & SC_TRACE_MASK_ENTER)
    case SC_TRACE_ENTER:
        (void)printf("  trace: enter state=%s slot=%d\n",
                     sm06_machine_effect_state_name(data->state), (int)data->activation_index);
        break;
#endif
#if (SC_MACHINE_TRACE_MASK & SC_TRACE_MASK_EXIT)
    case SC_TRACE_EXIT:
        (void)printf("  trace: exit state=%s slot=%d\n",
                     sm06_machine_effect_state_name(data->state), (int)data->activation_index);
        break;
#endif
#if (SC_MACHINE_TRACE_MASK & SC_TRACE_MASK_TRANSITION)
    case SC_TRACE_TRANSITION:
        (void)printf("  trace: transition #%d %s -[%s]-> %s action=%s slot=%d\n",
                     (int)data->transition_index,
                     sm06_machine_effect_state_name(data->source),
                     sm06_machine_effect_event_name(event->id),
                     sm06_machine_effect_state_name(data->target),
                     action_name(data->action),
                     (int)data->activation_index);
        break;
#endif
#if (SC_MACHINE_TRACE_MASK & SC_TRACE_MASK_GUARD)
    case SC_TRACE_GUARD:
        (void)printf("  trace: guard=%s state=%s result=%s\n",
                     guard_name(data->guard), sm06_machine_effect_state_name(data->state),
                     data->result ? "true" : "false");
        break;
#endif
#if (SC_MACHINE_TRACE_MASK & SC_TRACE_MASK_TIMER_CHECK)
    case SC_TRACE_TIMER_CHECK:
        (void)printf("  trace: timer state=%s slot=%d due=%s\n",
                     sm06_machine_effect_state_name(data->state),
                     (int)data->activation_index, data->result ? "true" : "false");
        break;
#endif
    default:
        break;
    }
}
#define SC_MACHINE_HAS_TRACE 1
#define SC_MACHINE_TRACE trace_hook
#endif

/* Instantiate the shared dispatch for this machine. */
#define SC_MACHINE_PREFIX sm06_machine_effect
#define SC_MACHINE_DEF machine_def
#define SC_MACHINE_GUARD guard_eval
#define SC_MACHINE_ACTION action_exec
#define SC_MACHINE_ACTIVE_CAPACITY SM06_MACHINE_EFFECT_ACTIVE_CAPACITY
#include "sc/sc_machine.h"
#undef SC_MACHINE_TRACE_MASK

