/*
 * machineeffect_statechart_config.c
 *
 * AUTO-GENERATED by sysmlc statix backend from state def 'MachineEffect'. DO NOT EDIT.
 */

#include "machineeffect_statechart_config.h"

/* Per-state entry/exit action table (indexed by state id). */
static const sc_state_def_t machineeffect_states[] = {
    {SC_ACTION_NONE, SC_ACTION_NONE},
    {SC_ACTION_NONE, SC_ACTION_NONE},
    {SC_ACTION_NONE, SC_ACTION_NONE},
};

/* Transition rows: {source, event, guard, action, target}. */
static const sc_transition_t machineeffect_transitions[] = {
    {MACHINEEFFECT_STATE_IDLE, SC_EVENT_COMPLETION, SC_GUARD_NONE, MACHINEEFFECT_ACTION_IDLE_COMPLETION_EFFECT, MACHINEEFFECT_STATE_ARMED},
    {MACHINEEFFECT_STATE_ARMED, SC_EVENT_COMPLETION, SC_GUARD_NONE, SC_ACTION_NONE, MACHINEEFFECT_STATE_RUNNING},
};

const sc_machine_t machineeffect_statechart_machine = {
    machineeffect_transitions,
    machineeffect_states,
    (uint16_t)(sizeof(machineeffect_transitions) / sizeof(machineeffect_transitions[0])),
    MACHINEEFFECT_STATE_COUNT,
    MACHINEEFFECT_STATE_IDLE,
};
