/*
 * sm06/machine_effect.c
 *
 * AUTO-GENERATED by sysmlc statix backend from state def 'SM06::MachineEffect'. DO NOT EDIT.
 */

#include "sm06/machine_effect.h"

/* Static state and transition tables (file-local). */
static const sc_state_def_t states[] = {
    {SC_ACTION_NONE, SC_ACTION_NONE, SC_STATE_INVALID, SC_STATE_INVALID, false},
    {SC_ACTION_NONE, SC_ACTION_NONE, SC_STATE_INVALID, SC_STATE_INVALID, false},
    {SC_ACTION_NONE, SC_ACTION_NONE, SC_STATE_INVALID, SC_STATE_INVALID, false},
};

static const sc_transition_t transitions[] = {
    {SM06_MACHINE_EFFECT_STATE_IDLE, SC_EVENT_COMPLETION, SC_GUARD_NONE, SM06_MACHINE_EFFECT_ACTION_IDLE_COMPLETION_EFFECT, SM06_MACHINE_EFFECT_STATE_ARMED},
    {SM06_MACHINE_EFFECT_STATE_ARMED, SC_EVENT_COMPLETION, SC_GUARD_NONE, SC_ACTION_NONE, SM06_MACHINE_EFFECT_STATE_RUNNING},
};

static const sc_invariant_t invariants[] = {
    {SC_STATE_INVALID, SC_GUARD_NONE}
};

static const sc_machine_t machine_def = {
    transitions,
    states,
    (uint16_t)(sizeof(transitions) / sizeof(transitions[0])),
    SM06_MACHINE_EFFECT_STATE_COUNT,
    SM06_MACHINE_EFFECT_STATE_IDLE,
    (sc_state_id_t)1u,
    invariants,
    (uint16_t)0u,
};

/* Generated guard/action dispatch. */
static bool guard_eval(sc_guard_id_t guard_id, const sc_runtime_t *runtime, const sc_event_t *event)
{
    (void)runtime;
    (void)event;
    (void)guard_id;
    return false;
}

static sc_status_t action_exec(sc_action_id_t action_id, sc_runtime_t *runtime, const sc_event_t *event)
{
    sm06_machine_effect_context_t *ctx = (sm06_machine_effect_context_t *)runtime->user_data;
    (void)event;
    if (ctx == NULL) { return SC_STATUS_INVALID_ARGUMENT; }
    switch (action_id) {
    case SM06_MACHINE_EFFECT_ACTION_IDLE_COMPLETION_EFFECT:
        ctx->counter = ctx->counter + 1;
        return SC_STATUS_OK;
    default:
        return SC_STATUS_ERROR;
    }
}

void sm06_machine_effect_context_init(sm06_machine_effect_context_t *ctx)
{
    if (ctx == NULL) {
        return;
    }
    *ctx = (sm06_machine_effect_context_t){.counter = 0};
}

const char *sm06_machine_effect_state_name(sc_state_id_t state)
{
    switch (state) {
    case SM06_MACHINE_EFFECT_STATE_IDLE:
        return "idle";
    case SM06_MACHINE_EFFECT_STATE_ARMED:
        return "armed";
    case SM06_MACHINE_EFFECT_STATE_RUNNING:
        return "running";
    case SC_STATE_INVALID:
        return "SC_STATE_INVALID";
    default:
        return "SC_STATE_UNKNOWN";
    }
}

const char *sm06_machine_effect_event_name(sc_event_id_t event)
{
    switch (event) {
    case SC_EVENT_COMPLETION:
        return "SC_EVENT_COMPLETION";
    case SC_EVENT_INVALID:
        return "SC_EVENT_INVALID";
    default:
        return "SC_EVENT_UNKNOWN";
    }
}

/* Instantiate the shared dispatch for this machine. */
#define SC_MACHINE_PREFIX sm06_machine_effect
#define SC_MACHINE_DEF machine_def
#define SC_MACHINE_GUARD guard_eval
#define SC_MACHINE_ACTION action_exec
#include "sc/sc_machine.h"
