/*
 * sm01_machine.c
 *
 * AUTO-GENERATED by sysmlc statix backend from state def 'SM01::Machine'. DO NOT EDIT.
 */

#include "sm01_machine.h"

/* Static state and transition tables. */
static const sc_state_def_t sm01_machine_states[] = {
    {SC_ACTION_NONE, SC_ACTION_NONE},
    {SC_ACTION_NONE, SC_ACTION_NONE},
};

static const sc_transition_t sm01_machine_transitions[] = {
    {SM01_MACHINE_STATE_IDLE, SC_EVENT_COMPLETION, SC_GUARD_NONE, SC_ACTION_NONE, SM01_MACHINE_STATE_RUNNING},
};

static const sc_machine_t sm01_machine_machine = {
    sm01_machine_transitions,
    sm01_machine_states,
    (uint16_t)(sizeof(sm01_machine_transitions) / sizeof(sm01_machine_transitions[0])),
    SM01_MACHINE_STATE_COUNT,
    SM01_MACHINE_STATE_IDLE,
};

/* Generated guard/action dispatch. */
static bool sm01_machine_guard_eval(sc_guard_id_t guard_id, const sc_runtime_t *runtime, const sc_event_t *event)
{
    (void)runtime;
    (void)event;
    (void)guard_id;
    return false;
}

static sc_status_t sm01_machine_action_exec(sc_action_id_t action_id, sc_runtime_t *runtime, const sc_event_t *event)
{
    (void)runtime;
    (void)event;
    (void)action_id;
    return SC_STATUS_OK;
}

void sm01_machine_context_init(sm01_machine_context_t *ctx)
{
    if (ctx == NULL) {
        return;
    }
    *ctx = (sm01_machine_context_t){0};
}

const char *sm01_machine_state_name(sc_state_id_t state)
{
    switch (state) {
    case SM01_MACHINE_STATE_IDLE:
        return "idle";
    case SM01_MACHINE_STATE_RUNNING:
        return "running";
    case SC_STATE_INVALID:
        return "SC_STATE_INVALID";
    default:
        return "SC_STATE_UNKNOWN";
    }
}

const char *sm01_machine_event_name(sc_event_id_t event)
{
    switch (event) {
    case SC_EVENT_COMPLETION:
        return "SC_EVENT_COMPLETION";
    case SC_EVENT_INVALID:
        return "SC_EVENT_INVALID";
    default:
        return "SC_EVENT_UNKNOWN";
    }
}

/* Instantiate the shared dispatch for this machine. */
#define SC_MACHINE_PREFIX sm01_machine
#define SC_MACHINE_DEF sm01_machine_machine
#define SC_MACHINE_GUARD sm01_machine_guard_eval
#define SC_MACHINE_ACTION sm01_machine_action_exec
#include "sc/sc_machine.h"
