#ifndef SM01_MACHINE_H
#define SM01_MACHINE_H

/*
 * sm01/machine.h
 *
 * AUTO-GENERATED by sysmlc statix backend from state def 'SM01::Machine'. DO NOT EDIT.
 */

#include "sc/sc_runtime.h"

#ifdef __cplusplus
extern "C" {
#endif

/// @brief Generated state identifiers.
typedef enum sm01_machine_state_e {
    SM01_MACHINE_STATE_IDLE = 0, ///< @brief State 'idle'.
    SM01_MACHINE_STATE_RUNNING = 1 ///< @brief State 'running'.
} sm01_machine_state_t;

#define SM01_MACHINE_STATE_COUNT 2u

/// @brief Generated signal event identifiers.
/* (none defined in this model) */

/// @brief Generated guard identifiers.
/* (none defined in this model) */

/// @brief Generated action identifiers.
/* (none defined in this model) */


#define SM01_MACHINE_QUEUE_CAPACITY 8u

/// @brief Generated context for SM01::Machine.
typedef struct sm01_machine_context_s {
    uint8_t _unused; ///< @brief Placeholder for empty context.
} sm01_machine_context_t;

/// @brief Runtime instance for SM01::Machine.
typedef struct sm01_machine_s {
    sc_runtime_t runtime;
} sm01_machine_t;

/// @brief Initialize a generated context object with model default values.
/// @param ctx Context object to initialize.
void sm01_machine_context_init(sm01_machine_context_t *ctx);

/// @brief Initialize a statechart instance and enter its initial state.
/// @param sm Statechart instance to initialize.
/// @param ctx Context object owned by the caller.
/// @return SC_STATUS_OK on success, or an error status.
sc_status_t sm01_machine_init(sm01_machine_t *sm, sm01_machine_context_t *ctx);

/// @brief Dispatch one event into the statechart.
/// @param sm Statechart instance receiving the event.
/// @param event Event to dispatch.
/// @return SC_STATUS_OK if a transition fired, SC_STATUS_NO_TRANSITION if none matched, or an error status.
sc_status_t sm01_machine_dispatch(sm01_machine_t *sm, const sc_event_t *event);

/// @brief Dispatch one no-payload event by id.
/// @param sm Statechart instance receiving the event.
/// @param event_id Event identifier to dispatch.
/// @return SC_STATUS_OK if a transition fired, SC_STATUS_NO_TRANSITION if none matched, or an error status.
sc_status_t sm01_machine_post(sm01_machine_t *sm, sc_event_id_t event_id);

/// @brief Return the currently active state.
/// @param sm Statechart instance to inspect.
/// @return Active state id, or SC_STATE_INVALID before initialization.
sc_state_id_t sm01_machine_get_state(const sm01_machine_t *sm);

/// @brief Return a stable name for a generated state id.
/// @param state State identifier to name.
/// @return Static non-NULL state name.
const char *sm01_machine_state_name(sc_state_id_t state);

/// @brief Return a stable name for a generated event id.
/// @param event Event identifier to name.
/// @return Static non-NULL event name.
const char *sm01_machine_event_name(sc_event_id_t event);

#ifdef __cplusplus
}
#endif

#endif /* SM01_MACHINE_H */
