/*
 * machine_actions.c
 *
 * AUTO-GENERATED by sysmlc statix backend from state def 'Machine'. DO NOT EDIT.
 */

#include "machine_statechart_ids.h"
#include "machine_context.h"
#include "sc/sc_runtime.h"

bool sc_guard_eval(sc_guard_id_t guard_id, const sc_runtime_t *runtime, const sc_event_t *event)
{
    (void)runtime;
    (void)event;
    (void)guard_id;
    return false;
}

sc_status_t sc_action_exec(sc_action_id_t action_id, sc_runtime_t *runtime, const sc_event_t *event)
{
    (void)runtime;
    (void)event;
    (void)action_id;
    return SC_STATUS_OK;
}
