#ifndef MACHINE_STATECHART_IDS_H
#define MACHINE_STATECHART_IDS_H

/*
 * machine_statechart_ids.h
 *
 * AUTO-GENERATED by sysmlc statix backend from state def 'Machine'. DO NOT EDIT.
 */

/* States */
typedef enum machine_state_e {
    MACHINE_STATE_IDLE = 0,
    MACHINE_STATE_RUNNING = 1
} machine_state_t;

#define MACHINE_STATE_COUNT 2u

/* Events */
/* (none defined in this model) */

/* Guards */
/* (none defined in this model) */

/* Actions */
/* (none defined in this model) */

#endif /* MACHINE_STATECHART_IDS_H */
