#ifndef SM05_MACHINECHAINNESTED_H
#define SM05_MACHINECHAINNESTED_H

/*
 * sm05/machinechainnested.h
 *
 * AUTO-GENERATED by sysmlc statix backend from state def 'SM05::MachineChainNested'. DO NOT EDIT.
 */

#include "sc/sc_runtime.h"

#ifdef __cplusplus
extern "C" {
#endif

/// @brief Generated state identifiers.
typedef enum sm05_machinechainnested_state_e {
    SM05_MACHINECHAINNESTED_STATE_IDLE = 0, ///< @brief State 'idle'.
    SM05_MACHINECHAINNESTED_STATE_RUNNING = 1 ///< @brief State 'running'.
} sm05_machinechainnested_state_t;

#define SM05_MACHINECHAINNESTED_STATE_COUNT 2u

/// @brief Generated signal event identifiers.
/* (none defined in this model) */

/// @brief Generated guard identifiers.
typedef enum sm05_machinechainnested_guard_e {
    SM05_MACHINECHAINNESTED_GUARD_G0 = 1 ///< @brief Generated guard 'g0'.
} sm05_machinechainnested_guard_t;

/// @brief Generated action identifiers.
/* (none defined in this model) */


#define SM05_MACHINECHAINNESTED_QUEUE_CAPACITY 8u

/// @brief Generated nested context type sm05_machinechainnested_inner_t.
typedef struct {
    double z;
} sm05_machinechainnested_inner_t;

/// @brief Generated nested context type sm05_machinechainnested_box_t.
typedef struct {
    sm05_machinechainnested_inner_t inner;
} sm05_machinechainnested_box_t;

/// @brief Generated context for SM05::MachineChainNested.
typedef struct sm05_machinechainnested_context_s {
    sm05_machinechainnested_box_t box;
} sm05_machinechainnested_context_t;

/// @brief Runtime instance for SM05::MachineChainNested.
typedef struct sm05_machinechainnested_s {
    sc_runtime_t runtime;
} sm05_machinechainnested_t;

/// @brief Initialize a generated context object with model default values.
/// @param ctx Context object to initialize.
void sm05_machinechainnested_context_init(sm05_machinechainnested_context_t *ctx);

/// @brief Initialize a statechart instance and enter its initial state.
/// @param sm Statechart instance to initialize.
/// @param ctx Context object owned by the caller.
/// @return SC_STATUS_OK on success, or an error status.
sc_status_t sm05_machinechainnested_init(sm05_machinechainnested_t *sm, sm05_machinechainnested_context_t *ctx);

/// @brief Dispatch one event into the statechart.
/// @param sm Statechart instance receiving the event.
/// @param event Event to dispatch.
/// @return SC_STATUS_OK if a transition fired, SC_STATUS_NO_TRANSITION if none matched, or an error status.
sc_status_t sm05_machinechainnested_dispatch(sm05_machinechainnested_t *sm, const sc_event_t *event);

/// @brief Dispatch one no-payload event by id.
/// @param sm Statechart instance receiving the event.
/// @param event_id Event identifier to dispatch.
/// @return SC_STATUS_OK if a transition fired, SC_STATUS_NO_TRANSITION if none matched, or an error status.
sc_status_t sm05_machinechainnested_post(sm05_machinechainnested_t *sm, sc_event_id_t event_id);

/// @brief Return the currently active state.
/// @param sm Statechart instance to inspect.
/// @return Active state id, or SC_STATE_INVALID before initialization.
sc_state_id_t sm05_machinechainnested_get_state(const sm05_machinechainnested_t *sm);

/// @brief Return a stable name for a generated state id.
/// @param state State identifier to name.
/// @return Static non-NULL state name.
const char *sm05_machinechainnested_state_name(sc_state_id_t state);

/// @brief Return a stable name for a generated event id.
/// @param event Event identifier to name.
/// @return Static non-NULL event name.
const char *sm05_machinechainnested_event_name(sc_event_id_t event);

#ifdef __cplusplus
}
#endif

#endif /* SM05_MACHINECHAINNESTED_H */
