/*
 * sm05/machine_chain_nested.c
 *
 * AUTO-GENERATED by sysmlc statix backend from state def 'SM05::MachineChainNested'. DO NOT EDIT.
 */

#include "sm05/machine_chain_nested.h"

/* Static state and transition tables (file-local). */
static const sc_state_def_t states[] = {
    {SC_ACTION_NONE, SC_ACTION_NONE, SC_STATE_INVALID, SC_STATE_INVALID, false},
    {SC_ACTION_NONE, SC_ACTION_NONE, SC_STATE_INVALID, SC_STATE_INVALID, false},
};

static const sc_transition_t transitions[] = {
    {SM05_MACHINE_CHAIN_NESTED_STATE_IDLE, SC_EVENT_COMPLETION, SM05_MACHINE_CHAIN_NESTED_GUARD_G0, SC_ACTION_NONE, SM05_MACHINE_CHAIN_NESTED_STATE_RUNNING},
};

static const sc_invariant_t invariants[] = {
    {SC_STATE_INVALID, SC_GUARD_NONE}
};

static const sc_machine_t machine_def = {
    transitions,
    states,
    (uint16_t)(sizeof(transitions) / sizeof(transitions[0])),
    SM05_MACHINE_CHAIN_NESTED_STATE_COUNT,
    SM05_MACHINE_CHAIN_NESTED_STATE_IDLE,
    (sc_state_id_t)1u,
    invariants,
    (uint16_t)0u,
};

/* Generated guard/action dispatch. */
static bool guard_eval(sc_guard_id_t guard_id, const sc_runtime_t *runtime, const sc_event_t *event)
{
    const sm05_machine_chain_nested_context_t *ctx = (const sm05_machine_chain_nested_context_t *)runtime->user_data;
    (void)event;
    switch (guard_id) {
    case SM05_MACHINE_CHAIN_NESTED_GUARD_G0:
        return ctx->box.inner.z > 0.0;
    default:
        return false;
    }
}

static sc_status_t action_exec(sc_action_id_t action_id, sc_runtime_t *runtime, const sc_event_t *event)
{
    (void)runtime;
    (void)event;
    (void)action_id;
    return SC_STATUS_OK;
}

void sm05_machine_chain_nested_context_init(sm05_machine_chain_nested_context_t *ctx)
{
    if (ctx == NULL) {
        return;
    }
    *ctx = (sm05_machine_chain_nested_context_t){.box = {.inner = {.z = 0.25}}};
}

const char *sm05_machine_chain_nested_state_name(sc_state_id_t state)
{
    switch (state) {
    case SM05_MACHINE_CHAIN_NESTED_STATE_IDLE:
        return "idle";
    case SM05_MACHINE_CHAIN_NESTED_STATE_RUNNING:
        return "running";
    case SC_STATE_INVALID:
        return "SC_STATE_INVALID";
    default:
        return "SC_STATE_UNKNOWN";
    }
}

const char *sm05_machine_chain_nested_event_name(sc_event_id_t event)
{
    switch (event) {
    case SC_EVENT_COMPLETION:
        return "SC_EVENT_COMPLETION";
    case SC_EVENT_INVALID:
        return "SC_EVENT_INVALID";
    default:
        return "SC_EVENT_UNKNOWN";
    }
}

/* Instantiate the shared dispatch for this machine. */
#define SC_MACHINE_PREFIX sm05_machine_chain_nested
#define SC_MACHINE_DEF machine_def
#define SC_MACHINE_GUARD guard_eval
#define SC_MACHINE_ACTION action_exec
#include "sc/sc_machine.h"
