/*
 * sm05/machine_chain_nested_runner.c
 *
 * AUTO-GENERATED by sysmlc statix backend from state def 'SM05::MachineChainNested'. DO NOT EDIT.
 */

#include "sm05/machine_chain_nested.h"

#include <stdio.h>
#include <string.h>

static bool sm05_machine_chain_nested_event_from_name(const char *name, sc_event_id_t *event_id)
{
    if ((name == NULL) || (event_id == NULL)) {
        return false;
    }
    return false;
}

int main(int argc, char **argv)
{
    sm05_machine_chain_nested_context_t ctx;
    sm05_machine_chain_nested_t sm;
    sc_status_t status;
    int i;

    sm05_machine_chain_nested_context_init(&ctx);
    status = sm05_machine_chain_nested_init(&sm, &ctx);
    (void)printf("init status=%s state=%s final=%d\n", sc_status_str(status),
                 sm05_machine_chain_nested_state_name(sm05_machine_chain_nested_get_state(&sm)), (int)sm05_machine_chain_nested_is_final(&sm));
    if (status != SC_STATUS_OK) {
        return 1;
    }

    for (i = 1; i < argc; ++i) {
        sc_event_id_t event_id = SC_EVENT_INVALID;
        if (!sm05_machine_chain_nested_event_from_name(argv[i], &event_id)) {
            (void)fprintf(stderr, "unknown event: %s\n", argv[i]);
            return 2;
        }
        status = sm05_machine_chain_nested_post(&sm, event_id);
        (void)printf("event %s status=%s state=%s final=%d\n", argv[i],
                     sc_status_str(status), sm05_machine_chain_nested_state_name(sm05_machine_chain_nested_get_state(&sm)), (int)sm05_machine_chain_nested_is_final(&sm));
        if ((status != SC_STATUS_OK) && (status != SC_STATUS_NO_TRANSITION)) {
            return 1;
        }
    }
    return 0;
}
