/*
 * sm05/machine_chain_nested_runner.c
 *
 * AUTO-GENERATED by sysmlc statix backend from state def 'SM05::MachineChainNested'. DO NOT EDIT.
 */

#include "sm05/machine_chain_nested.h"

#include <stdio.h>
#include <string.h>

static bool sm05_machine_chain_nested_event_from_name(const char *name, sc_event_id_t *event_id)
{
    if ((name == NULL) || (event_id == NULL)) {
        return false;
    }
    return false;
}

static void sm05_machine_chain_nested_print_configuration(const sm05_machine_chain_nested_t *sm)
{
    sc_state_id_t count = sm05_machine_chain_nested_active_count(sm);
    sc_state_id_t i;
    (void)printf(" configuration=");
    for (i = 0; i < count; ++i) {
        if (i > 0) {
            (void)printf(",");
        }
        (void)printf("%s", sm05_machine_chain_nested_state_name(sm05_machine_chain_nested_active_state(sm, i)));
    }
}

int main(int argc, char **argv)
{
    sm05_machine_chain_nested_context_t ctx;
    sm05_machine_chain_nested_t sm;
    sc_status_t status;
    int i;

    sm05_machine_chain_nested_context_init(&ctx);
    status = sm05_machine_chain_nested_init(&sm, &ctx);
    (void)printf("init status=%s state=%s final=%d ctx.box.inner.z=%g", sc_status_str(status),
                 sm05_machine_chain_nested_state_name(sm05_machine_chain_nested_get_state(&sm)), (int)sm05_machine_chain_nested_is_final(&sm), ctx.box.inner.z);
    sm05_machine_chain_nested_print_configuration(&sm);
    (void)printf("\n");
    if (status != SC_STATUS_OK) {
        return 1;
    }

    for (i = 1; i < argc; ++i) {
        sc_event_id_t event_id = SC_EVENT_INVALID;
        if (!sm05_machine_chain_nested_event_from_name(argv[i], &event_id)) {
            (void)fprintf(stderr, "unknown event: %s\n", argv[i]);
            return 2;
        }
        status = sm05_machine_chain_nested_post(&sm, event_id);
        (void)printf("event %s status=%s state=%s final=%d ctx.box.inner.z=%g", argv[i],
                     sc_status_str(status), sm05_machine_chain_nested_state_name(sm05_machine_chain_nested_get_state(&sm)), (int)sm05_machine_chain_nested_is_final(&sm), ctx.box.inner.z);
        sm05_machine_chain_nested_print_configuration(&sm);
        (void)printf("\n");
        if ((status != SC_STATUS_OK) && (status != SC_STATUS_NO_TRANSITION)) {
            return 1;
        }
    }
    return 0;
}
