#ifndef MACHINECHAINNESTED_CONTEXT_H
#define MACHINECHAINNESTED_CONTEXT_H

/*
 * machinechainnested_context.h
 *
 * AUTO-GENERATED by sysmlc statix backend from state def 'MachineChainNested'. DO NOT EDIT.
 */

#include "sc/sc_types.h"

typedef struct {
    double z;
} machinechainnested_inner_t;

typedef struct {
    machinechainnested_inner_t inner;
} machinechainnested_box_t;

typedef struct machinechainnested_context_s {
    machinechainnested_box_t box;
} machinechainnested_context_t;

#endif /* MACHINECHAINNESTED_CONTEXT_H */
