#ifndef MACHINECHAINNESTED_STATECHART_IDS_H
#define MACHINECHAINNESTED_STATECHART_IDS_H

/*
 * machinechainnested_statechart_ids.h
 *
 * AUTO-GENERATED by sysmlc statix backend from state def 'MachineChainNested'. DO NOT EDIT.
 */

/* States */
typedef enum machinechainnested_state_e {
    MACHINECHAINNESTED_STATE_IDLE = 0,
    MACHINECHAINNESTED_STATE_RUNNING = 1
} machinechainnested_state_t;

#define MACHINECHAINNESTED_STATE_COUNT 2u

/* Events */
/* (none defined in this model) */

/* Guards */
typedef enum machinechainnested_guard_e {
    MACHINECHAINNESTED_GUARD_G0 = 1
} machinechainnested_guard_t;

/* Actions */
/* (none defined in this model) */

#endif /* MACHINECHAINNESTED_STATECHART_IDS_H */
