/*
 * machinechainnested_statechart_config.c
 *
 * AUTO-GENERATED by sysmlc statix backend from state def 'MachineChainNested'. DO NOT EDIT.
 */

#include "machinechainnested_statechart_config.h"

/* Per-state entry/exit action table (indexed by state id). */
static const sc_state_def_t machinechainnested_states[] = {
    {SC_ACTION_NONE, SC_ACTION_NONE},
    {SC_ACTION_NONE, SC_ACTION_NONE},
};

/* Transition rows: {source, event, guard, action, target}. */
static const sc_transition_t machinechainnested_transitions[] = {
    {MACHINECHAINNESTED_STATE_IDLE, SC_EVENT_COMPLETION, MACHINECHAINNESTED_GUARD_G0, SC_ACTION_NONE, MACHINECHAINNESTED_STATE_RUNNING},
};

const sc_machine_t machinechainnested_statechart_machine = {
    machinechainnested_transitions,
    machinechainnested_states,
    (uint16_t)(sizeof(machinechainnested_transitions) / sizeof(machinechainnested_transitions[0])),
    MACHINECHAINNESTED_STATE_COUNT,
    MACHINECHAINNESTED_STATE_IDLE,
};
