/*
 * machinechainnested_actions.c
 *
 * AUTO-GENERATED by sysmlc statix backend from state def 'MachineChainNested'. DO NOT EDIT.
 */

#include "machinechainnested_statechart_ids.h"
#include "machinechainnested_context.h"
#include "sc/sc_runtime.h"

bool sc_guard_eval(sc_guard_id_t guard_id, const sc_runtime_t *runtime, const sc_event_t *event)
{
    const machinechainnested_context_t *ctx = (const machinechainnested_context_t *)runtime->user_data;
    (void)event;
    switch (guard_id) {
    case MACHINECHAINNESTED_GUARD_G0:
        return ctx->box.inner.z > 0.0;
    default:
        return false;
    }
}

sc_status_t sc_action_exec(sc_action_id_t action_id, sc_runtime_t *runtime, const sc_event_t *event)
{
    (void)runtime;
    (void)event;
    (void)action_id;
    return SC_STATUS_OK;
}
