from __future__ import annotations

from jinja2 import Environment, PackageLoader

from sysmlc.backends.statix.builder import _c_identifier
from sysmlc.backends.statix.program import COMPLETION_EVENT, CProgram, CProject

_env = Environment(
    loader=PackageLoader("sysmlc.backends.statix", "templates"),
    autoescape=False,  # generating C, never HTML
    trim_blocks=True,
    lstrip_blocks=True,
    keep_trailing_newline=True,
)

_FIRST_STATE_ID = 0
_FIRST_NONZERO_ID = 1


def _paths(program: CProgram) -> tuple[str, str]:
    """Return ``(package_dir, file_stem)`` for a program's output paths.

    ``SM01::Machine`` becomes ``("sm01", "machine")``. A nested package
    ``A::B::Machine`` becomes ``("a_b", "machine")``. Derived with the same
    snake_case sanitizer that builds ``program.prefix``, so paths and symbols
    stay in lockstep.
    """
    package, _, stem = program.qualified_name.rpartition("::")
    return _c_identifier(package), _c_identifier(stem)


def _const(prefix: str, kind: str, name: str) -> str:
    return f"{prefix.upper()}_{kind}_{_c_identifier(name).upper()}"


def _banner(filename: str, name: str) -> str:
    return (
        f"/*\n * {filename}\n *\n"
        f" * AUTO-GENERATED by sysmlc statix backend from state def '{name}'."
        " DO NOT EDIT.\n */\n"
    )


def _state_entries(program: CProgram) -> list[tuple[str, int]]:
    return [
        (_const(program.prefix, "STATE", s.name), _FIRST_STATE_ID + i)
        for i, s in enumerate(program.states)
    ]


def _event_entries(program: CProgram) -> list[tuple[str, int]]:
    return [
        (_const(program.prefix, "EVENT", e), _FIRST_NONZERO_ID + i)
        for i, e in enumerate(program.events)
    ]


def _guard_entries(program: CProgram) -> list[tuple[str, int]]:
    return [
        (_const(program.prefix, "GUARD", g.name), _FIRST_NONZERO_ID + i)
        for i, g in enumerate(program.guards)
    ]


def _action_entries(program: CProgram) -> list[tuple[str, int]]:
    return [
        (_const(program.prefix, "ACTION", a.name), _FIRST_NONZERO_ID + i)
        for i, a in enumerate(program.actions)
    ]


def _event_token(program: CProgram, event: str) -> str:
    if event == COMPLETION_EVENT:
        return "SC_EVENT_COMPLETION"
    return _const(program.prefix, "EVENT", event)


def _context_initializer(program: CProgram) -> str:
    if not program.context.fields:
        return "{0}"
    parts = ", ".join(f".{f.name} = {f.init}" for f in program.context.fields)
    return "{" + parts + "}"


def emit_context_initializer(program: CProgram) -> str:
    """Return a C initializer literal for the generated context struct."""
    return _context_initializer(program)


def _enum_view(
    base: str, entries: list[tuple[str, int]], docs: dict[str, str]
) -> dict[str, object]:
    return {
        "base": base,
        "entries": [
            {"const": const, "value": value, "doc": docs.get(const, const)}
            for const, value in entries
        ],
    }


def _header_view(program: CProgram) -> dict[str, object]:
    p = program.prefix
    pkg_dir, stem = _paths(program)
    state_docs = {
        _const(p, "STATE", s.name): f"State '{s.name}'" for s in program.states
    }
    event_docs = {
        _const(p, "EVENT", e): f"Signal event '{e}'" for e in program.events
    }
    guard_docs = {
        _const(p, "GUARD", g.name): f"Generated guard '{g.name}'"
        for g in program.guards
    }
    action_docs = {
        _const(p, "ACTION", a.name): f"Generated action '{a.name}'"
        for a in program.actions
    }
    return {
        "guard": f"{p.upper()}_H",
        "banner": _banner(f"{pkg_dir}/{stem}.h", program.qualified_name),
        "prefix": p,
        "qn": program.qualified_name,
        "state_count": len(program.states),
        "queue_capacity": program.queue_capacity,
        "enums": [
            _enum_view(f"{p}_state", _state_entries(program), state_docs),
            _enum_view(f"{p}_event", _event_entries(program), event_docs),
            _enum_view(f"{p}_guard", _guard_entries(program), guard_docs),
            _enum_view(f"{p}_action", _action_entries(program), action_docs),
        ],
        "structs": [
            {
                "name": st.name,
                "fields": [
                    {"c_type": f.c_type, "name": f.name} for f in st.fields
                ],
            }
            for st in program.context.structs
        ],
        "context_fields": [
            {"c_type": f.c_type, "name": f.name} for f in program.context.fields
        ],
    }


def emit_header(program: CProgram) -> str:
    """Render the generated public statechart header."""
    return _env.get_template("machine.h.j2").render(**_header_view(program))


def emit_source(program: CProgram) -> str:
    """Render the generated statechart implementation."""
    p = program.prefix
    pkg_dir, stem = _paths(program)
    parts = [
        _banner(f"{pkg_dir}/{stem}.c", program.qualified_name),
        f'#include "{pkg_dir}/{stem}.h"',
        "",
        "/* Static state and transition tables (file-local). */",
        "static const sc_state_def_t states[] = {",
    ]
    for s in program.states:
        entry = (
            "SC_ACTION_NONE"
            if s.entry_action_id is None
            else _const(p, "ACTION", s.entry_action_id)
        )
        exit_ = (
            "SC_ACTION_NONE"
            if s.exit_action_id is None
            else _const(p, "ACTION", s.exit_action_id)
        )
        parent = (
            "SC_STATE_INVALID"
            if s.parent is None
            else _const(p, "STATE", s.parent)
        )
        initial_child = (
            "SC_STATE_INVALID"
            if s.initial_child is None
            else _const(p, "STATE", s.initial_child)
        )
        is_final = "true" if s.is_final else "false"
        parts.append(
            f"    {{{entry}, {exit_}, {parent}, {initial_child}, {is_final}}},"
        )
    parts += [
        "};",
        "",
        "static const sc_transition_t transitions[] = {",
    ]
    for t in program.transitions:
        source = _const(p, "STATE", t.source)
        event = _event_token(program, t.event)
        guard = (
            "SC_GUARD_NONE" if t.guard is None else _const(p, "GUARD", t.guard)
        )
        action = (
            "SC_ACTION_NONE"
            if t.action is None
            else _const(p, "ACTION", t.action)
        )
        target = _const(p, "STATE", t.target)
        parts.append(f"    {{{source}, {event}, {guard}, {action}, {target}}},")
    parts += [
        "};",
        "",
        "static const sc_machine_t machine_def = {",
        "    transitions,",
        "    states,",
        "    (uint16_t)(sizeof(transitions) / sizeof(transitions[0])),",
        f"    {p.upper()}_STATE_COUNT,",
        f"    {_const(p, 'STATE', program.initial)},",
        f"    (sc_state_id_t){program.max_depth}u,",
        "};",
        "",
        "/* Generated guard/action dispatch. */",
        (
            "static bool guard_eval(sc_guard_id_t guard_id, "
            "const sc_runtime_t *runtime, const sc_event_t *event)"
        ),
        "{",
    ]
    if program.guards:
        parts += [
            (
                f"    const {p}_context_t *ctx = "
                f"(const {p}_context_t *)runtime->user_data;"
            ),
            "    (void)event;",
            "    switch (guard_id) {",
        ]
        for g in program.guards:
            parts.append(f"    case {_const(p, 'GUARD', g.name)}:")
            parts.append(f"        return {g.expr};")
        parts += ["    default:", "        return false;", "    }"]
    else:
        parts += [
            "    (void)runtime;",
            "    (void)event;",
            "    (void)guard_id;",
            "    return false;",
        ]
    parts += [
        "}",
        "",
        (
            "static sc_status_t action_exec("
            "sc_action_id_t action_id, sc_runtime_t *runtime, "
            "const sc_event_t *event)"
        ),
        "{",
    ]
    if program.actions:
        parts += [
            f"    {p}_context_t *ctx = ({p}_context_t *)runtime->user_data;",
            "    (void)event;",
            "    if (ctx == NULL) { return SC_STATUS_INVALID_ARGUMENT; }",
            "    switch (action_id) {",
        ]
        for a in program.actions:
            parts.append(f"    case {_const(p, 'ACTION', a.name)}:")
            for stmt in a.statements:
                parts.append(f"        {stmt}")
            parts.append("        return SC_STATUS_OK;")
        parts += ["    default:", "        return SC_STATUS_ERROR;", "    }"]
    else:
        parts += [
            "    (void)runtime;",
            "    (void)event;",
            "    (void)action_id;",
            "    return SC_STATUS_OK;",
        ]
    parts += [
        "}",
        "",
        f"void {p}_context_init({p}_context_t *ctx)",
        "{",
        "    if (ctx == NULL) {",
        "        return;",
        "    }",
        f"    *ctx = ({p}_context_t){_context_initializer(program)};",
        "}",
        "",
        f"const char *{p}_state_name(sc_state_id_t state)",
        "{",
        "    switch (state) {",
    ]
    for s in program.states:
        parts.append(f"    case {_const(p, 'STATE', s.name)}:")
        parts.append(f'        return "{s.name}";')
    parts += [
        "    case SC_STATE_INVALID:",
        '        return "SC_STATE_INVALID";',
        "    default:",
        '        return "SC_STATE_UNKNOWN";',
        "    }",
        "}",
        "",
        f"const char *{p}_event_name(sc_event_id_t event)",
        "{",
        "    switch (event) {",
    ]
    for e in program.events:
        parts.append(f"    case {_const(p, 'EVENT', e)}:")
        parts.append(f'        return "{e}";')
    parts += [
        "    case SC_EVENT_COMPLETION:",
        '        return "SC_EVENT_COMPLETION";',
        "    case SC_EVENT_INVALID:",
        '        return "SC_EVENT_INVALID";',
        "    default:",
        '        return "SC_EVENT_UNKNOWN";',
        "    }",
        "}",
        "",
        "/* Instantiate the shared dispatch for this machine. */",
        f"#define SC_MACHINE_PREFIX {p}",
        "#define SC_MACHINE_DEF machine_def",
        "#define SC_MACHINE_GUARD guard_eval",
        "#define SC_MACHINE_ACTION action_exec",
        '#include "sc/sc_machine.h"',
    ]
    return "\n".join(parts) + "\n"


def _runner_view(program: CProgram) -> dict[str, object]:
    p = program.prefix
    pkg_dir, stem = _paths(program)
    return {
        "banner": _banner(f"{pkg_dir}/{stem}_runner.c", program.qualified_name),
        "pkg_dir": pkg_dir,
        "stem": stem,
        "prefix": p,
        "events": [
            {"name": e, "const": _const(p, "EVENT", e)} for e in program.events
        ],
    }


def emit_runner(program: CProgram) -> str:
    """Render a minimal hosted-C runner for smoke execution on a PC."""
    return _env.get_template("runner.c.j2").render(**_runner_view(program))


def _cmakelists_view(project: CProject) -> dict[str, str]:
    lib_sources = "\n".join(
        f"  src/{d}/{s}.c" for d, s in (_paths(p) for p in project.programs)
    )
    runners = []
    for program in project.programs:
        pkg_dir, stem = _paths(program)
        runners.append(
            f"add_executable({program.prefix}_runner "
            f"host/{pkg_dir}/{stem}_runner.c)\n"
            f"target_link_libraries({program.prefix}_runner "
            "statix_statecharts)"
        )
    runners_tail = (
        ("\n" if project.programs else "")
        + "\n\n".join(runners)
        + ("\n" if runners else "")
    )
    return {"lib_sources": lib_sources, "runners_tail": runners_tail}


def emit_cmakelists(project: CProject) -> str:
    """Render a CMakeLists.txt building runtime, statecharts, and runners."""
    return _env.get_template("cmakelists.txt.j2").render(
        **_cmakelists_view(project)
    )


def emit_project_files(project: CProject) -> dict[str, str]:
    """Return {relative-output-path: content} for the generated C project."""
    files: dict[str, str] = {}
    for program in project.programs:
        pkg_dir, stem = _paths(program)
        files[f"include/{pkg_dir}/{stem}.h"] = emit_header(program)
        files[f"src/{pkg_dir}/{stem}.c"] = emit_source(program)
        files[f"host/{pkg_dir}/{stem}_runner.c"] = emit_runner(program)
    files["CMakeLists.txt"] = emit_cmakelists(project)
    return files


def emit_files(program: CProgram) -> dict[str, str]:
    """Return {filename: content} for a single generated statechart project."""
    return emit_project_files(CProject(programs=(program,)))


def to_c_preview(artifact: CProgram | CProject) -> str:
    """Concatenate generated units in a stable order (for ``-f c`` preview)."""
    project = (
        artifact if isinstance(artifact, CProject) else CProject((artifact,))
    )
    files = emit_project_files(project)
    order: list[str] = []
    for program in project.programs:
        pkg_dir, stem = _paths(program)
        order += [
            f"include/{pkg_dir}/{stem}.h",
            f"src/{pkg_dir}/{stem}.c",
            f"host/{pkg_dir}/{stem}_runner.c",
        ]
    return "\n".join(f"/* ==== {name} ==== */\n{files[name]}" for name in order)
