from __future__ import annotations

from sysmlc.backends.statix.program import COMPLETION_EVENT, CProgram

_FIRST_STATE_ID = 0
_FIRST_NONZERO_ID = 1


def _const(prefix: str, kind: str, name: str) -> str:
    return f"{prefix.upper()}_{kind}_{name.upper()}"


def _enum_block(base: str, entries: list[tuple[str, int]]) -> str:
    if not entries:
        return "/* (none defined in this model) */\n"
    lines = [f"typedef enum {base}_e {{"]
    for i, (const_name, value) in enumerate(entries):
        comma = "," if i + 1 < len(entries) else ""
        lines.append(f"    {const_name} = {value}{comma}")
    lines.append(f"}} {base}_t;\n")
    return "\n".join(lines)


def _banner(filename: str, name: str) -> str:
    return (
        f"/*\n * {filename}\n *\n"
        f" * AUTO-GENERATED by sysmlc statix backend from state def '{name}'."
        " DO NOT EDIT.\n */\n"
    )


def emit_ids_h(program: CProgram) -> str:
    """Render the state/event/guard/action id enums header."""
    p = program.prefix
    guard = f"{p.upper()}_STATECHART_IDS_H"
    states = [
        (_const(p, "STATE", s.name), _FIRST_STATE_ID + i)
        for i, s in enumerate(program.states)
    ]
    events = [
        (_const(p, "EVENT", e), _FIRST_NONZERO_ID + i)
        for i, e in enumerate(program.events)
    ]
    guards = [
        (_const(p, "GUARD", g.name), _FIRST_NONZERO_ID + i)
        for i, g in enumerate(program.guards)
    ]
    actions = [
        (_const(p, "ACTION", a.name), _FIRST_NONZERO_ID + i)
        for i, a in enumerate(program.actions)
    ]
    parts = [
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
        _banner(f"{p}_statechart_ids.h", program.name),
        "/* States */",
        _enum_block(f"{p}_state", states),
        f"#define {p.upper()}_STATE_COUNT {len(states)}u",
        "",
        "/* Events */",
        _enum_block(f"{p}_event", events),
        "/* Guards */",
        _enum_block(f"{p}_guard", guards),
        "/* Actions */",
        _enum_block(f"{p}_action", actions),
        f"#endif /* {guard} */",
    ]
    return "\n".join(parts) + "\n"


def emit_config_h(program: CProgram) -> str:
    """Render the machine-declaration + queue-capacity config header."""
    p = program.prefix
    guard = f"{p.upper()}_STATECHART_CONFIG_H"
    parts = [
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
        _banner(f"{p}_statechart_config.h", program.name),
        '#include "sc/sc_runtime.h"',
        "",
        f'#include "{p}_statechart_ids.h"',
        "",
        f"#define {p.upper()}_QUEUE_CAPACITY {program.queue_capacity}u",
        "",
        f"extern const sc_machine_t {p}_statechart_machine;",
        "",
        f"#endif /* {guard} */",
    ]
    return "\n".join(parts) + "\n"


def _event_token(program: CProgram, event: str) -> str:
    if event == COMPLETION_EVENT:
        return "SC_EVENT_COMPLETION"
    return _const(program.prefix, "EVENT", event)


def emit_config_c(program: CProgram) -> str:
    """Render the per-state table, transition table, and machine literal."""
    p = program.prefix
    parts = [
        _banner(f"{p}_statechart_config.c", program.name),
        f'#include "{p}_statechart_config.h"',
        "",
        "/* Per-state entry/exit action table (indexed by state id). */",
        f"static const sc_state_def_t {p}_states[] = {{",
    ]
    for s in program.states:
        entry = (
            "SC_ACTION_NONE"
            if s.entry_action_id is None
            else _const(p, "ACTION", s.entry_action_id)
        )
        exit_ = (
            "SC_ACTION_NONE"
            if s.exit_action_id is None
            else _const(p, "ACTION", s.exit_action_id)
        )
        parts.append(f"    {{{entry}, {exit_}}},")
    parts += [
        "};",
        "",
        "/* Transition rows: {source, event, guard, action, target}. */",
        f"static const sc_transition_t {p}_transitions[] = {{",
    ]
    for t in program.transitions:
        source = _const(p, "STATE", t.source)
        event = _event_token(program, t.event)
        guard = (
            "SC_GUARD_NONE" if t.guard is None else _const(p, "GUARD", t.guard)
        )
        action = (
            "SC_ACTION_NONE"
            if t.action is None
            else _const(p, "ACTION", t.action)
        )
        target = _const(p, "STATE", t.target)
        parts.append(f"    {{{source}, {event}, {guard}, {action}, {target}}},")
    parts += [
        "};",
        "",
        f"const sc_machine_t {p}_statechart_machine = {{",
        f"    {p}_transitions,",
        f"    {p}_states,",
        f"    (uint16_t)(sizeof({p}_transitions) / "
        f"sizeof({p}_transitions[0])),",
        f"    {p.upper()}_STATE_COUNT,",
        f"    {_const(p, 'STATE', program.initial)},",
        "};",
    ]
    return "\n".join(parts) + "\n"


def emit_context_h(program: CProgram) -> str:
    """Render the generated context struct (and any nested structs)."""
    p = program.prefix
    guard = f"{p.upper()}_CONTEXT_H"
    parts = [
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
        _banner(f"{p}_context.h", program.name),
        '#include "sc/sc_types.h"',
        "",
    ]
    for struct in program.context.structs:
        parts.append("typedef struct {")
        for field in struct.fields:
            parts.append(f"    {field.c_type} {field.name};")
        parts.append(f"}} {struct.name};")
        parts.append("")
    parts.append(f"typedef struct {p}_context_s {{")
    for field in program.context.fields:
        parts.append(f"    {field.c_type} {field.name};")
    if not program.context.fields:
        parts.append("    uint8_t _unused; /* no attributes in this model */")
    parts.append(f"}} {p}_context_t;")
    parts += ["", f"#endif /* {guard} */"]
    return "\n".join(parts) + "\n"


def emit_context_initializer(program: CProgram) -> str:
    """A C initializer literal for the context struct (used by a demo main).

    Returns the bare type name when the machine has no attributes, so the
    caller can zero-initialize with ``{0}``.
    """
    p = program.prefix
    if not program.context.fields:
        return f"{p}_context_t"
    parts = ", ".join(f".{f.name} = {f.init}" for f in program.context.fields)
    return "{" + parts + "}"


def emit_actions_c(program: CProgram) -> str:
    """Render the fully-generated guard/action dispatch functions."""
    p = program.prefix
    parts = [
        _banner(f"{p}_actions.c", program.name),
        f'#include "{p}_statechart_ids.h"',
        f'#include "{p}_context.h"',
        '#include "sc/sc_runtime.h"',
        "",
        "bool sc_guard_eval(sc_guard_id_t guard_id, const sc_runtime_t "
        "*runtime, const sc_event_t *event)",
        "{",
    ]
    if program.guards:
        parts += [
            f"    const {p}_context_t *ctx = "
            f"(const {p}_context_t *)runtime->user_data;",
            "    (void)event;",
            "    switch (guard_id) {",
        ]
        for g in program.guards:
            parts.append(f"    case {_const(p, 'GUARD', g.name)}:")
            parts.append(f"        return {g.expr};")
        parts += ["    default:", "        return false;", "    }"]
    else:
        parts += [
            "    (void)runtime;",
            "    (void)event;",
            "    (void)guard_id;",
            "    return false;",
        ]
    parts += [
        "}",
        "",
        "sc_status_t sc_action_exec(sc_action_id_t action_id, sc_runtime_t "
        "*runtime, const sc_event_t *event)",
        "{",
    ]
    if program.actions:
        parts += [
            f"    {p}_context_t *ctx = ({p}_context_t *)runtime->user_data;",
            "    (void)event;",
            "    if (ctx == NULL) { return SC_STATUS_INVALID_ARGUMENT; }",
            "    switch (action_id) {",
        ]
        for a in program.actions:
            parts.append(f"    case {_const(p, 'ACTION', a.name)}:")
            for stmt in a.statements:
                parts.append(f"        {stmt}")
            parts.append("        return SC_STATUS_OK;")
        parts += ["    default:", "        return SC_STATUS_ERROR;", "    }"]
    else:
        parts += [
            "    (void)runtime;",
            "    (void)event;",
            "    (void)action_id;",
            "    return SC_STATUS_OK;",
        ]
    parts += ["}"]
    return "\n".join(parts) + "\n"


def emit_cmakelists(program: CProgram) -> str:
    """Render a CMakeLists.txt building the runtime + generated units."""
    p = program.prefix
    return (
        "cmake_minimum_required(VERSION 3.16)\n"
        f"project({p}_statechart C)\n\n"
        "set(CMAKE_C_STANDARD 99)\n"
        "set(CMAKE_C_STANDARD_REQUIRED ON)\n\n"
        "add_compile_options(-Wall -Wextra -Wpedantic -Wconversion"
        " -Wsign-conversion -Wdouble-promotion -Werror)\n\n"
        "include_directories(${CMAKE_CURRENT_SOURCE_DIR}/include)\n\n"
        f"add_library({p}_statechart STATIC\n"
        "  src/sc_status.c\n"
        "  src/sc_event_queue.c\n"
        "  src/sc_runtime.c\n"
        f"  {p}_statechart_config.c\n"
        f"  {p}_actions.c)\n"
    )


def emit_files(program: CProgram) -> dict[str, str]:
    """Return {filename: content} for the generated C project."""
    p = program.prefix
    return {
        f"{p}_statechart_ids.h": emit_ids_h(program),
        f"{p}_statechart_config.h": emit_config_h(program),
        f"{p}_statechart_config.c": emit_config_c(program),
        f"{p}_context.h": emit_context_h(program),
        f"{p}_actions.c": emit_actions_c(program),
        "CMakeLists.txt": emit_cmakelists(program),
    }


def to_c_preview(program: CProgram) -> str:
    """Concatenate generated units in a stable order (for ``-f c`` preview)."""
    files = emit_files(program)
    order = [
        f"{program.prefix}_statechart_ids.h",
        f"{program.prefix}_context.h",
        f"{program.prefix}_statechart_config.h",
        f"{program.prefix}_statechart_config.c",
        f"{program.prefix}_actions.c",
    ]
    return "\n".join(f"/* ==== {name} ==== */\n{files[name]}" for name in order)
