from __future__ import annotations

from typing import Final

from jinja2 import Environment, PackageLoader

from sysmlc.backends.statix.builder import _c_identifier
from sysmlc.backends.statix.payload import _walk_payload_fields
from sysmlc.backends.statix.program import (
    COMPLETION_EVENT,
    INTERNAL_TARGET,
    TIMEOUT_EVENT,
    CExternFunction,
    CProgram,
    CProject,
    CSend,
    CTimeout,
)

_TRACE_FORMATS: Final[dict[str, tuple[str, str]]] = {
    "bool": ("%d", "(int)"),
    "int32_t": ("%d", ""),
    "double": ("%g", ""),
}

_RUNTIME_IMPL_C: Final[str] = (
    "/// @file sc_runtime_impl.c\n"
    "/// @brief Single translation unit that instantiates the header-only\n"
    "/// sc_runtime.h implementation for this project. Do not add any other\n"
    "/// #define SC_RUNTIME_IMPLEMENTATION in this project -- exactly one is\n"
    "/// required and this is it.\n"
    "#define SC_RUNTIME_IMPLEMENTATION\n"
    '#include "sc/sc_runtime.h"\n'
)


def _trace_fields(program: CProgram) -> list[dict[str, str]]:
    """Flatten context fields for the runner's trace line.

    Args:
        program:
            The program to analyze.

    Returns:
        list[dict[str, str]]:
            Each dict has keys ``path``, ``fmt``, and ``cast``.

    """
    structs_by_name = {s.name: s for s in program.context.structs}

    def walk(path: str, c_type: str) -> list[dict[str, str]]:
        struct = structs_by_name.get(c_type)
        if struct is not None:
            out: list[dict[str, str]] = []
            for f in struct.fields:
                out += walk(f"{path}.{f.name}", f.c_type)
            return out
        fmt, cast = _TRACE_FORMATS.get(c_type, ("%d", "(int)"))
        return [{"path": path, "fmt": fmt, "cast": cast}]

    fields: list[dict[str, str]] = []
    for f in program.context.fields:
        fields += walk(f.name, f.c_type)
    return fields


_env = Environment(
    loader=PackageLoader("sysmlc.backends.statix", "templates"),
    autoescape=False,  # generating C, never HTML
    trim_blocks=True,
    lstrip_blocks=True,
    keep_trailing_newline=True,
)

_FIRST_STATE_ID = 0
_FIRST_NONZERO_ID = 1


def _paths(program: CProgram) -> tuple[str, str]:
    """Return ``(package_dir, file_stem)`` for a program's output paths.

    ``SM01::Machine`` becomes ``("sm01", "machine")``. A nested package
    ``A::B::Machine`` becomes ``("a_b", "machine")``. Derived with the same
    snake_case sanitizer that builds ``program.prefix``, so paths and symbols
    stay in lockstep.
    """
    package, _, stem = program.qualified_name.rpartition("::")
    return _c_identifier(package), _c_identifier(stem)


def _const(prefix: str, kind: str, name: str) -> str:
    return f"{prefix.upper()}_{kind}_{_c_identifier(name).upper()}"


def _banner(filename: str, name: str) -> str:
    return (
        f"/*\n * {filename}\n *\n"
        f" * AUTO-GENERATED by sysmlc statix backend from state def '{name}'."
        " DO NOT EDIT.\n */\n"
    )


def _state_entries(program: CProgram) -> list[tuple[str, int]]:
    return [
        (_const(program.prefix, "STATE", s.name), _FIRST_STATE_ID + i)
        for i, s in enumerate(program.states)
    ]


def _event_entries(program: CProgram) -> list[tuple[str, int]]:
    return [
        (_const(program.prefix, "EVENT", e), _FIRST_NONZERO_ID + i)
        for i, e in enumerate(program.events)
    ]


def _guard_entries(program: CProgram) -> list[tuple[str, int]]:
    return [
        (_const(program.prefix, "GUARD", g.name), _FIRST_NONZERO_ID + i)
        for i, g in enumerate(program.guards)
    ]


def _action_entries(program: CProgram) -> list[tuple[str, int]]:
    return [
        (_const(program.prefix, "ACTION", a.name), _FIRST_NONZERO_ID + i)
        for i, a in enumerate(program.actions)
    ]


def _event_token(program: CProgram, event: str) -> str:
    if event == COMPLETION_EVENT:
        return "SC_EVENT_COMPLETION"
    if event == TIMEOUT_EVENT:
        return "SC_EVENT_TIMEOUT"
    return _const(program.prefix, "EVENT", event)


def _context_initializer(program: CProgram) -> str:
    if not program.context.fields:
        return "{0}"
    parts = ", ".join(f".{f.name} = {f.init}" for f in program.context.fields)
    return "{" + parts + "}"


def _timeout_case_lines(t: CTimeout) -> list[str]:
    if t.literal_ticks is not None:
        deadline = t.literal_ticks
        if t.is_at:
            return [
                (
                    "return (runtime->active[activation_index].entered_at "
                    f"<= {deadline}) && (runtime->now >= {deadline});"
                ),
            ]
        return [
            (
                "return (runtime->now - "
                "runtime->active[activation_index].entered_at) >= "
                f"{deadline};"
            ),
        ]
    assert t.attr_expr is not None
    lines = [
        "{",
        "    sc_time_t deadline;",
        f"    if (!sc_seconds_to_ticks({t.attr_expr}, &deadline)) {{",
        "        return false;",
        "    }",
    ]
    if t.is_at:
        lines.append(
            "    return (runtime->active[activation_index].entered_at "
            "<= deadline) && (runtime->now >= deadline);"
        )
    else:
        lines.append(
            "    return (runtime->now - "
            "runtime->active[activation_index].entered_at) >= deadline;"
        )
    lines.append("}")
    return lines


def emit_context_initializer(program: CProgram) -> str:
    """Return a C initializer literal for the generated context struct."""
    return _context_initializer(program)


def _enum_view(
    base: str, entries: list[tuple[str, int]], docs: dict[str, str]
) -> dict[str, object]:
    return {
        "base": base,
        "entries": [
            {"const": const, "value": value, "doc": docs.get(const, const)}
            for const, value in entries
        ],
    }


def _header_view(program: CProgram) -> dict[str, object]:
    p = program.prefix
    pkg_dir, stem = _paths(program)
    state_docs = {
        _const(p, "STATE", s.name): f"State '{s.name}'" for s in program.states
    }
    event_docs = {
        _const(p, "EVENT", e): f"Signal event '{e}'" for e in program.events
    }
    guard_docs = {
        _const(p, "GUARD", g.name): f"Generated guard '{g.name}'"
        for g in program.guards
    }
    action_docs = {
        _const(p, "ACTION", a.name): f"Generated action '{a.name}'"
        for a in program.actions
    }
    return {
        "guard": f"{p.upper()}_H",
        "banner": _banner(f"{pkg_dir}/{stem}.h", program.qualified_name),
        "prefix": p,
        "qn": program.qualified_name,
        "state_count": len(program.states),
        "queue_capacity": program.queue_capacity,
        "active_capacity": program.active_capacity,
        "has_send": program.has_send,
        "has_timer": program.has_timer,
        "has_when": program.has_when,
        "enums": [
            _enum_view(f"{p}_state", _state_entries(program), state_docs),
            _enum_view(f"{p}_event", _event_entries(program), event_docs),
            _enum_view(f"{p}_guard", _guard_entries(program), guard_docs),
            _enum_view(f"{p}_action", _action_entries(program), action_docs),
        ],
        "generated_enums": [
            _enum_view(
                e.base,
                [(const, i) for i, const in enumerate(e.literals)],
                {},
            )
            for e in program.enums
        ],
        "structs": [
            {
                "name": st.name,
                "fields": [
                    {"c_type": f.c_type, "name": f.name} for f in st.fields
                ],
            }
            for st in program.context.structs
        ],
        "context_fields": [
            {"c_type": f.c_type, "name": f.name} for f in program.context.fields
        ],
    }


def emit_header(program: CProgram) -> str:
    """Render the generated public statechart header."""
    return _env.get_template("machine.h.j2").render(**_header_view(program))


def _source_view(program: CProgram) -> dict[str, object]:
    p = program.prefix
    pkg_dir, stem = _paths(program)

    def act(action_id: str | None) -> str:
        return (
            "SC_ACTION_NONE"
            if action_id is None
            else _const(p, "ACTION", action_id)
        )

    def st(state_name: str | None) -> str:
        return (
            "SC_STATE_INVALID"
            if state_name is None
            else _const(p, "STATE", state_name)
        )

    def stmt_lines(statement: str | CSend) -> list[str]:
        if isinstance(statement, CSend):
            token = _event_token(program, statement.event)
            if statement.payload_lines:
                lines = [
                    line.replace("__EVENT_TOKEN__", token)
                    for line in statement.payload_lines
                ]
                return ["{", *(f"    {line}" for line in lines), "}"]
            token = _event_token(program, statement.event)
            if statement.value_expr is None:
                call = [
                    "    sc_status_t send_status = sc_runtime_enqueue(",
                    f"        runtime, (sc_event_id_t){token});",
                ]
            else:
                call = [
                    "    sc_status_t send_status = sc_runtime_enqueue_f64(",
                    f"        runtime, (sc_event_id_t){token},",
                    f"        {statement.value_expr});",
                ]
            return [
                "{",
                *call,
                "    if (send_status != SC_STATUS_OK) {",
                "        return send_status;",
                "    }",
                "}",
            ]
        return [statement]

    def region_ref(value: int | None) -> str:
        if value is None:
            return "SC_STATE_INVALID"
        return f"(sc_state_id_t){value}u"

    state_rows = [
        {
            "entry": act(s.entry_action_id),
            "exit": act(s.exit_action_id),
            "parent": st(s.parent),
            "initial_child": st(s.initial_child),
            "is_final": "true" if s.is_final else "false",
            "slot": f"(sc_state_id_t){s.slot}u",
            "region_first": region_ref(s.region_first),
            "region_count": f"(sc_state_id_t){s.region_count}u",
        }
        for s in program.states
    ]
    regions_rows = [_const(p, "STATE", name) for name in program.regions]
    transition_rows = [
        {
            "source": _const(p, "STATE", t.source),
            "event": _event_token(program, t.event),
            "guard": "SC_GUARD_NONE"
            if t.guard is None
            else _const(p, "GUARD", t.guard),
            "action": act(t.action),
            "target": "SC_STATE_INVALID"
            if t.target == INTERNAL_TARGET
            else _const(p, "STATE", t.target),
        }
        for t in program.transitions
    ]
    return {
        "banner": _banner(f"{pkg_dir}/{stem}.c", program.qualified_name),
        "pkg_dir": pkg_dir,
        "stem": stem,
        "prefix": p,
        "needs_math": program.needs_math,
        "has_send": program.has_send,
        "has_extern": bool(program.extern_functions),
        "state_rows": state_rows,
        "transition_rows": transition_rows,
        "state_count_macro": f"{p.upper()}_STATE_COUNT",
        "initial_const": _const(p, "STATE", program.initial),
        "max_depth": program.max_depth,
        "invariant_rows": [
            {"scope": st(inv.scope), "guard": _const(p, "GUARD", inv.guard)}
            for inv in program.invariants
        ],
        "invariant_count": len(program.invariants),
        "guards": [
            {
                "const": _const(p, "GUARD", g.name),
                "expr": g.expr,
                "name": g.name,
            }
            for g in program.guards
        ],
        "guards_use_ctx": any("ctx->" in g.expr for g in program.guards),
        "has_timer": program.has_timer,
        "timeouts_use_ctx": program.timeouts_use_ctx,
        "has_when": program.has_when,
        "when_count": program.when_count,
        "regions_rows": regions_rows,
        "region_row_count": len(program.regions),
        "active_capacity": program.active_capacity,
        "timeout_rows": [
            {"state": st(t.source), "lines": _timeout_case_lines(t)}
            for t in program.timeouts
        ],
        "actions": [
            {
                "const": _const(p, "ACTION", a.name),
                "statements": [
                    line for s in a.statements for line in stmt_lines(s)
                ],
                "name": a.name,
            }
            for a in program.actions
        ],
        "context_initializer": _context_initializer(program),
        "state_names": [
            {"const": _const(p, "STATE", s.name), "name": s.name}
            for s in program.states
        ],
        "event_names": [
            {"const": _const(p, "EVENT", e), "name": e} for e in program.events
        ],
    }


def emit_source(program: CProgram) -> str:
    """Render the generated statechart implementation."""
    return _env.get_template("machine.c.j2").render(**_source_view(program))


def _initial_configuration(program: CProgram) -> set[str]:
    """Every state name active immediately after _init, before any event.

    Walks program.initial down through initial_child (and, at a parallel
    container, into every region root's own initial_child chain) -- the
    exact set _init/_descend enter. Used to find which transitions are
    genuinely reachable "from here" for the generated example command.
    """
    by_name = {s.name: s for s in program.states}
    configuration: set[str] = set()
    frontier = [program.initial]
    while frontier:
        name = frontier.pop()
        if name in configuration:
            continue
        configuration.add(name)
        state = by_name[name]
        if state.region_count and state.region_first is not None:
            frontier.extend(
                program.regions[
                    state.region_first : state.region_first + state.region_count
                ]
            )
        elif state.initial_child is not None:
            frontier.append(state.initial_child)
    return configuration


def _example_command(program: CProgram) -> dict[str, object]:
    """Select the generated --help example, per the documented fallback tiers.

    1. An externally-triggered transition reachable from the initial
       configuration -- a genuinely meaningful example.
    2. Else, if the machine has a timer with at least one literal (not
       attribute-derived) deadline, a --tick example using that literal
       expression (rendered at C runtime, since it depends on the compiled
       SC_TICKS_PER_SECOND -- never a Python-computed decimal).
    3. Else, if the model has any external event at all, the first one,
       explicitly labeled syntax-only (not guaranteed to transition).
    4. Else, no meaningful example exists; the help text notes running with
       no arguments alone settles the machine.
    """
    configuration = _initial_configuration(program)
    for t in program.transitions:
        if (t.source in configuration) and (t.event in program.events):
            return {"kind": "reachable", "event": t.event}
    if program.has_timer:
        for timeout in program.timeouts:
            if timeout.literal_ticks is not None:
                return {"kind": "timed", "tick_expr": timeout.literal_ticks}
    if program.events:
        return {"kind": "syntax_only", "event": program.events[0]}
    return {"kind": "none"}


def _runner_view(program: CProgram) -> dict[str, object]:
    p = program.prefix
    pkg_dir, stem = _paths(program)
    return {
        "banner": _banner(f"{pkg_dir}/{stem}_runner.c", program.qualified_name),
        "pkg_dir": pkg_dir,
        "stem": stem,
        "prefix": p,
        "has_timer": program.has_timer,
        "events": [
            {"name": e, "const": _const(p, "EVENT", e)} for e in program.events
        ],
        "trace_fields": _trace_fields(program),
        "qualified_name": program.qualified_name,
        "initial_state": program.initial,
        "help_state_rows": [
            {
                "name": s.name,
                "is_initial": s.name == program.initial,
                "is_final": s.is_final,
            }
            for s in program.states
        ],
        "help_transition_rows": [
            {
                "source": t.source,
                "event": "(completion)"
                if t.event == COMPLETION_EVENT
                else "(timeout)"
                if t.event == TIMEOUT_EVENT
                else t.event,
                "guard": t.guard or "-",
                "action": t.action or "-",
                "target": t.target,
            }
            for t in program.transitions
        ],
        "region_names": list(program.regions),
        "active_capacity": program.active_capacity,
        "example": _example_command(program),
    }


def emit_runner(program: CProgram) -> str:
    """Render a minimal hosted-C runner for smoke execution on a PC."""
    return _env.get_template("runner.c.j2").render(**_runner_view(program))


def _cmakelists_view(project: CProject) -> dict[str, object]:
    lib_sources = "\n".join(
        f"  src/{d}/{s}.c" for d, s in (_paths(p) for p in project.programs)
    )
    runners = []
    for program in project.programs:
        pkg_dir, stem = _paths(program)
        runners.append(
            f"add_executable({program.prefix}_runner "
            f"host/{pkg_dir}/{stem}_runner.c)\n"
            f"target_link_libraries({program.prefix}_runner "
            "statix_statecharts)"
        )
    runners_tail = (
        ("\n" if project.programs else "")
        + "\n\n".join(runners)
        + ("\n" if runners else "")
    )
    needs_math = any(p.needs_math for p in project.programs)
    structs_by_name = {
        s.name: s for p in project.programs for s in p.context.structs
    }
    payload_leaf_counts = [
        len(_walk_payload_fields(name, structs_by_name))
        for p in project.programs
        for name in p.payload_struct_types
    ]
    required_bytes = (
        8 if not payload_leaf_counts else 8 * max(payload_leaf_counts)
    )
    return {
        "lib_sources": lib_sources,
        "runners_tail": runners_tail,
        "math_lib": " m" if needs_math else "",
        "has_extern": any(p.extern_functions for p in project.programs),
        "payload_size": required_bytes if required_bytes > 8 else None,
    }


def emit_cmakelists(project: CProject) -> str:
    """Render a CMakeLists.txt building runtime, statecharts, and runners."""
    return _env.get_template("cmakelists.txt.j2").render(
        **_cmakelists_view(project)
    )


def _extern_header(project: CProject) -> str | None:
    """Render include/statix_extern.h, or None if nothing needs it.

    Deduped by CExternFunction.name across every program in the project --
    the same calc called from two different generated machines must
    resolve to exactly one declaration, not a duplicate/conflicting one.
    """
    seen: dict[str, CExternFunction] = {}
    for program in project.programs:
        for fn in program.extern_functions:
            seen.setdefault(fn.name, fn)
    if not seen:
        return None
    lines = [
        "#ifndef STATIX_EXTERN_H",
        "#define STATIX_EXTERN_H",
        "",
        "/*",
        " * AUTO-GENERATED by sysmlc statix backend. DO NOT EDIT.",
        " *",
        " * Declares every bodyless `calc def` used by this project as an",
        " * extern C function. Provide src/extern_impl.c implementing each",
        " * one -- statix never generates, overwrites, or deletes that file.",
        " */",
        "",
        '#include "sc/sc_types.h"',
    ]
    for program in project.programs:
        pkg_dir, stem = _paths(program)
        lines.append(f'#include "{pkg_dir}/{stem}.h"')
    lines += [
        "",
        "#ifdef __cplusplus",
        'extern "C" {',
        "#endif",
        "",
    ]
    for fn in seen.values():
        params = ", ".join(
            f"{t} {n}"
            for t, n in zip(fn.param_types, fn.param_names, strict=True)
        )
        lines.append(f"/* {fn.name} */")
        lines.append(f"{fn.return_type} {fn.c_name}({params});")
        lines.append("")
    lines += [
        "#ifdef __cplusplus",
        "}",
        "#endif",
        "",
        "#endif /* STATIX_EXTERN_H */",
    ]
    return "\n".join(lines) + "\n"


def emit_project_files(project: CProject) -> dict[str, str]:
    """Return {relative-output-path: content} for the generated C project."""
    files: dict[str, str] = {}
    for program in project.programs:
        pkg_dir, stem = _paths(program)
        files[f"include/{pkg_dir}/{stem}.h"] = emit_header(program)
        files[f"src/{pkg_dir}/{stem}.c"] = emit_source(program)
        files[f"host/{pkg_dir}/{stem}_runner.c"] = emit_runner(program)
    files["src/sc_runtime_impl.c"] = _RUNTIME_IMPL_C
    extern_header = _extern_header(project)
    if extern_header is not None:
        files["include/statix_extern.h"] = extern_header
    files["CMakeLists.txt"] = emit_cmakelists(project)
    return files


def emit_files(program: CProgram) -> dict[str, str]:
    """Return {filename: content} for a single generated statechart project."""
    return emit_project_files(CProject(programs=(program,)))


def to_c_preview(artifact: CProgram | CProject) -> str:
    """Concatenate generated units in a stable order (for ``-f c`` preview)."""
    project = (
        artifact if isinstance(artifact, CProject) else CProject((artifact,))
    )
    files = emit_project_files(project)
    order: list[str] = []
    for program in project.programs:
        pkg_dir, stem = _paths(program)
        order += [
            f"include/{pkg_dir}/{stem}.h",
            f"src/{pkg_dir}/{stem}.c",
            f"host/{pkg_dir}/{stem}_runner.c",
        ]
    return "\n".join(f"/* ==== {name} ==== */\n{files[name]}" for name in order)
