#ifndef SM03_MACHINE_REF_H
#define SM03_MACHINE_REF_H

/*
 * sm03/machine_ref.h
 *
 * AUTO-GENERATED by sysmlc statix backend from state def 'SM03::MachineRef'. DO NOT EDIT.
 */

#include "sc/sc_runtime.h"

#ifdef __cplusplus
extern "C" {
#endif

/// @brief Generated state identifiers.
typedef enum sm03_machine_ref_state_e {
    SM03_MACHINE_REF_STATE_IDLE = 0, ///< @brief State 'idle'.
    SM03_MACHINE_REF_STATE_RUNNING = 1 ///< @brief State 'running'.
} sm03_machine_ref_state_t;

#define SM03_MACHINE_REF_STATE_COUNT 2u

/// @brief Generated signal event identifiers.
/* (none defined in this model) */

/// @brief Generated guard identifiers.
typedef enum sm03_machine_ref_guard_e {
    SM03_MACHINE_REF_GUARD_G0 = 1 ///< @brief Generated guard 'g0'.
} sm03_machine_ref_guard_t;

/// @brief Generated action identifiers.
/* (none defined in this model) */


#define SM03_MACHINE_REF_QUEUE_CAPACITY 8u
#define SM03_MACHINE_REF_ACTIVE_CAPACITY 1u

/// @brief Generated context for SM03::MachineRef.
typedef struct sm03_machine_ref_context_s {
    bool enabled;
} sm03_machine_ref_context_t;

/// @brief Runtime instance for SM03::MachineRef.
typedef struct sm03_machine_ref_s {
    sc_runtime_t runtime;
    sc_activation_t active[SM03_MACHINE_REF_ACTIVE_CAPACITY];
} sm03_machine_ref_t;

/// @brief Initialize a generated context object with model default values.
/// @param ctx Context object to initialize.
void sm03_machine_ref_context_init(sm03_machine_ref_context_t *ctx);

/// @brief Initialize a statechart instance and enter its initial state.
/// @param sm Statechart instance to initialize.
/// @param ctx Context object owned by the caller.
/// @return SC_STATUS_OK on success, or an error status.
sc_status_t sm03_machine_ref_init(sm03_machine_ref_t *sm, sm03_machine_ref_context_t *ctx);

/// @brief Dispatch one event into the statechart.
/// @param sm Statechart instance receiving the event.
/// @param event Event to dispatch.
/// @return SC_STATUS_OK if a transition fired, SC_STATUS_NO_TRANSITION if none matched, or an error status.
sc_status_t sm03_machine_ref_dispatch(sm03_machine_ref_t *sm, const sc_event_t *event);

/// @brief Dispatch one no-payload event by id.
/// @param sm Statechart instance receiving the event.
/// @param event_id Event identifier to dispatch.
/// @return SC_STATUS_OK if a transition fired, SC_STATUS_NO_TRANSITION if none matched, or an error status.
sc_status_t sm03_machine_ref_post(sm03_machine_ref_t *sm, sc_event_id_t event_id);

/// @brief Return the currently active state.
/// @param sm Statechart instance to inspect.
/// @return Active state id, or SC_STATE_INVALID before initialization.
sc_state_id_t sm03_machine_ref_get_state(const sm03_machine_ref_t *sm);

/// @brief Whether the machine reached a root-level final state (terminated).
/// @param sm Statechart instance to inspect.
/// @return true if the active leaf is a root-scope final state.
bool sm03_machine_ref_is_final(const sm03_machine_ref_t *sm);

/// @brief Number of currently active true leaves.
/// @param sm Statechart instance to inspect.
/// @return Count of active true leaves, or 0 before initialization.
sc_state_id_t sm03_machine_ref_active_count(const sm03_machine_ref_t *sm);

/// @brief The k-th currently active true leaf, in ascending slot order.
/// @param sm Statechart instance to inspect.
/// @param index Which active leaf to return, 0 <= index < sm03_machine_ref_active_count(sm).
/// @return The index-th active leaf, or SC_STATE_INVALID if out of range.
sc_state_id_t sm03_machine_ref_active_state(const sm03_machine_ref_t *sm, sc_state_id_t index);

/// @brief Return a stable name for a generated state id.
/// @param state State identifier to name.
/// @return Static non-NULL state name.
const char *sm03_machine_ref_state_name(sc_state_id_t state);

/// @brief Return a stable name for a generated event id.
/// @param event Event identifier to name.
/// @return Static non-NULL event name.
const char *sm03_machine_ref_event_name(sc_event_id_t event);

#ifdef __cplusplus
}
#endif

#endif /* SM03_MACHINE_REF_H */
