/*
 * machineref_statechart_config.c
 *
 * AUTO-GENERATED by sysmlc statix backend from state def 'MachineRef'. DO NOT EDIT.
 */

#include "machineref_statechart_config.h"

/* Per-state entry/exit action table (indexed by state id). */
static const sc_state_def_t machineref_states[] = {
    {SC_ACTION_NONE, SC_ACTION_NONE},
    {SC_ACTION_NONE, SC_ACTION_NONE},
};

/* Transition rows: {source, event, guard, action, target}. */
static const sc_transition_t machineref_transitions[] = {
    {MACHINEREF_STATE_IDLE, SC_EVENT_COMPLETION, MACHINEREF_GUARD_G0, SC_ACTION_NONE, MACHINEREF_STATE_RUNNING},
};

const sc_machine_t machineref_statechart_machine = {
    machineref_transitions,
    machineref_states,
    (uint16_t)(sizeof(machineref_transitions) / sizeof(machineref_transitions[0])),
    MACHINEREF_STATE_COUNT,
    MACHINEREF_STATE_IDLE,
};
