#ifndef MACHINEREF_STATECHART_IDS_H
#define MACHINEREF_STATECHART_IDS_H

/*
 * machineref_statechart_ids.h
 *
 * AUTO-GENERATED by sysmlc statix backend from state def 'MachineRef'. DO NOT EDIT.
 */

/* States */
typedef enum machineref_state_e {
    MACHINEREF_STATE_IDLE = 0,
    MACHINEREF_STATE_RUNNING = 1
} machineref_state_t;

#define MACHINEREF_STATE_COUNT 2u

/* Events */
/* (none defined in this model) */

/* Guards */
typedef enum machineref_guard_e {
    MACHINEREF_GUARD_G0 = 1
} machineref_guard_t;

/* Actions */
/* (none defined in this model) */

#endif /* MACHINEREF_STATECHART_IDS_H */
