#ifndef MACHINEREF_CONTEXT_H
#define MACHINEREF_CONTEXT_H

/*
 * machineref_context.h
 *
 * AUTO-GENERATED by sysmlc statix backend from state def 'MachineRef'. DO NOT EDIT.
 */

#include "sc/sc_types.h"

typedef struct machineref_context_s {
    bool enabled;
} machineref_context_t;

#endif /* MACHINEREF_CONTEXT_H */
