/*
 * sm03/machineref.c
 *
 * AUTO-GENERATED by sysmlc statix backend from state def 'SM03::MachineRef'. DO NOT EDIT.
 */

#include "sm03/machineref.h"

/* Static state and transition tables. */
static const sc_state_def_t sm03_machineref_states[] = {
    {SC_ACTION_NONE, SC_ACTION_NONE},
    {SC_ACTION_NONE, SC_ACTION_NONE},
};

static const sc_transition_t sm03_machineref_transitions[] = {
    {SM03_MACHINEREF_STATE_IDLE, SC_EVENT_COMPLETION, SM03_MACHINEREF_GUARD_G0, SC_ACTION_NONE, SM03_MACHINEREF_STATE_RUNNING},
};

static const sc_machine_t sm03_machineref_machine = {
    sm03_machineref_transitions,
    sm03_machineref_states,
    (uint16_t)(sizeof(sm03_machineref_transitions) / sizeof(sm03_machineref_transitions[0])),
    SM03_MACHINEREF_STATE_COUNT,
    SM03_MACHINEREF_STATE_IDLE,
};

/* Generated guard/action dispatch. */
static bool sm03_machineref_guard_eval(sc_guard_id_t guard_id, const sc_runtime_t *runtime, const sc_event_t *event)
{
    const sm03_machineref_context_t *ctx = (const sm03_machineref_context_t *)runtime->user_data;
    (void)event;
    switch (guard_id) {
    case SM03_MACHINEREF_GUARD_G0:
        return ctx->enabled;
    default:
        return false;
    }
}

static sc_status_t sm03_machineref_action_exec(sc_action_id_t action_id, sc_runtime_t *runtime, const sc_event_t *event)
{
    (void)runtime;
    (void)event;
    (void)action_id;
    return SC_STATUS_OK;
}

void sm03_machineref_context_init(sm03_machineref_context_t *ctx)
{
    if (ctx == NULL) {
        return;
    }
    *ctx = (sm03_machineref_context_t){.enabled = true};
}

const char *sm03_machineref_state_name(sc_state_id_t state)
{
    switch (state) {
    case SM03_MACHINEREF_STATE_IDLE:
        return "idle";
    case SM03_MACHINEREF_STATE_RUNNING:
        return "running";
    case SC_STATE_INVALID:
        return "SC_STATE_INVALID";
    default:
        return "SC_STATE_UNKNOWN";
    }
}

const char *sm03_machineref_event_name(sc_event_id_t event)
{
    switch (event) {
    case SC_EVENT_COMPLETION:
        return "SC_EVENT_COMPLETION";
    case SC_EVENT_INVALID:
        return "SC_EVENT_INVALID";
    default:
        return "SC_EVENT_UNKNOWN";
    }
}

/* Instantiate the shared dispatch for this machine. */
#define SC_MACHINE_PREFIX sm03_machineref
#define SC_MACHINE_DEF sm03_machineref_machine
#define SC_MACHINE_GUARD sm03_machineref_guard_eval
#define SC_MACHINE_ACTION sm03_machineref_action_exec
#include "sc/sc_machine.h"
