/*
 * sm03_machineref.c
 *
 * AUTO-GENERATED by sysmlc statix backend from state def 'SM03::MachineRef'. DO NOT EDIT.
 */

#include "sm03_machineref.h"

/* Static state and transition tables. */
static const sc_state_def_t sm03_machineref_states[] = {
    {SC_ACTION_NONE, SC_ACTION_NONE},
    {SC_ACTION_NONE, SC_ACTION_NONE},
};

static const sc_transition_t sm03_machineref_transitions[] = {
    {SM03_MACHINEREF_STATE_IDLE, SC_EVENT_COMPLETION, SM03_MACHINEREF_GUARD_G0, SC_ACTION_NONE, SM03_MACHINEREF_STATE_RUNNING},
};

static const sc_machine_t sm03_machineref_machine = {
    sm03_machineref_transitions,
    sm03_machineref_states,
    (uint16_t)(sizeof(sm03_machineref_transitions) / sizeof(sm03_machineref_transitions[0])),
    SM03_MACHINEREF_STATE_COUNT,
    SM03_MACHINEREF_STATE_IDLE,
};

/* Generated guard/action dispatch. */
static bool sm03_machineref_guard_eval(sc_guard_id_t guard_id, const sc_runtime_t *runtime, const sc_event_t *event)
{
    const sm03_machineref_context_t *ctx = (const sm03_machineref_context_t *)runtime->user_data;
    (void)event;
    switch (guard_id) {
    case SM03_MACHINEREF_GUARD_G0:
        return ctx->enabled;
    default:
        return false;
    }
}

static sc_status_t sm03_machineref_action_exec(sc_action_id_t action_id, sc_runtime_t *runtime, const sc_event_t *event)
{
    (void)runtime;
    (void)event;
    (void)action_id;
    return SC_STATUS_OK;
}

/* Private dispatch helpers. */
static sc_status_t sm03_machineref_run_state_action(sm03_machineref_t *sm, sc_action_id_t action, const sc_event_t *event)
{
    if (action == SC_ACTION_NONE) {
        return SC_STATUS_OK;
    }
    return sm03_machineref_action_exec(action, &sm->runtime, event);
}

static int32_t sm03_machineref_find_transition(const sc_machine_t *machine, sc_state_id_t state, sc_event_id_t event_id, const sm03_machineref_t *sm, const sc_event_t *event)
{
    uint16_t limit = machine->transition_count;
    uint16_t i;
    if (limit > (uint16_t)SC_MAX_TRANSITIONS) {
        limit = (uint16_t)SC_MAX_TRANSITIONS;
    }
    for (i = 0u; i < limit; ++i) {
        const sc_transition_t *t = &machine->transitions[i];
        if ((t->source == state) && (t->event == event_id)) {
            bool enabled = (t->guard == SC_GUARD_NONE) ? true : sm03_machineref_guard_eval(t->guard, &sm->runtime, event);
            if (enabled) {
                return (int32_t)i;
            }
        }
    }
    return -1;
}

static sc_status_t sm03_machineref_take_transition(sm03_machineref_t *sm, const sc_transition_t *t, const sc_event_t *event)
{
    const sc_machine_t *machine = sm->runtime.machine;
    sc_status_t status;

    status = sm03_machineref_run_state_action(sm, machine->states[sm->runtime.current_state].exit_action, event);
    if (status != SC_STATUS_OK) {
        return status;
    }
    if (t->action != SC_ACTION_NONE) {
        status = sm03_machineref_action_exec(t->action, &sm->runtime, event);
        if (status != SC_STATUS_OK) {
            return status;
        }
    }
    sm->runtime.current_state = t->target;
    return sm03_machineref_run_state_action(sm, machine->states[t->target].entry_action, event);
}

static sc_status_t sm03_machineref_run_completion(sm03_machineref_t *sm)
{
    const sc_machine_t *machine = sm->runtime.machine;
    sc_event_t completion;
    uint16_t step;
    (void)sc_event_init(&completion, SC_EVENT_COMPLETION);
    for (step = 0u; step < (uint16_t)SC_MAX_RTC_STEPS; ++step) {
        int32_t idx = sm03_machineref_find_transition(machine, sm->runtime.current_state, SC_EVENT_COMPLETION, sm, &completion);
        sc_status_t status;
        if (idx < 0) {
            return SC_STATUS_OK;
        }
        status = sm03_machineref_take_transition(sm, &machine->transitions[idx], &completion);
        if (status != SC_STATUS_OK) {
            return status;
        }
    }
    return SC_STATUS_STEP_LIMIT;
}

/* Public API. */
void sm03_machineref_context_init(sm03_machineref_context_t *ctx)
{
    if (ctx == NULL) {
        return;
    }
    *ctx = (sm03_machineref_context_t){.enabled = true};
}

sc_status_t sm03_machineref_init(sm03_machineref_t *sm, sm03_machineref_context_t *ctx)
{
    sc_status_t status;
    sc_event_t completion;
    if ((sm == NULL) || (ctx == NULL)) {
        return SC_STATUS_INVALID_ARGUMENT;
    }
    status = sc_runtime_bind(&sm->runtime, &sm03_machineref_machine, ctx);
    if (status != SC_STATUS_OK) {
        return status;
    }
    (void)sc_event_init(&completion, SC_EVENT_COMPLETION);
    status = sm03_machineref_run_state_action(sm, sm03_machineref_machine.states[sm03_machineref_machine.initial_state].entry_action, &completion);
    if (status != SC_STATUS_OK) {
        return status;
    }
    return sm03_machineref_run_completion(sm);
}

sc_status_t sm03_machineref_dispatch(sm03_machineref_t *sm, const sc_event_t *event)
{
    const sc_machine_t *machine;
    int32_t idx;
    sc_status_t status;
    if ((sm == NULL) || (event == NULL) || (!sm->runtime.initialized)) {
        return SC_STATUS_INVALID_ARGUMENT;
    }
    machine = sm->runtime.machine;
    if ((machine == NULL) || (machine->transitions == NULL) || (machine->states == NULL)) {
        return SC_STATUS_INVALID_ARGUMENT;
    }
    idx = sm03_machineref_find_transition(machine, sm->runtime.current_state, event->id, sm, event);
    if (idx < 0) {
        return SC_STATUS_NO_TRANSITION;
    }
    status = sm03_machineref_take_transition(sm, &machine->transitions[idx], event);
    if (status != SC_STATUS_OK) {
        return status;
    }
    return sm03_machineref_run_completion(sm);
}

sc_status_t sm03_machineref_post(sm03_machineref_t *sm, sc_event_id_t event_id)
{
    sc_event_t event;
    sc_status_t status = sc_event_init(&event, event_id);
    if (status != SC_STATUS_OK) {
        return status;
    }
    return sm03_machineref_dispatch(sm, &event);
}

sc_state_id_t sm03_machineref_get_state(const sm03_machineref_t *sm)
{
    sc_state_id_t state = SC_STATE_INVALID;
    if (sm == NULL) {
        return SC_STATE_INVALID;
    }
    (void)sc_runtime_get_state(&sm->runtime, &state);
    return state;
}

const char *sm03_machineref_state_name(sc_state_id_t state)
{
    switch (state) {
    case SM03_MACHINEREF_STATE_IDLE:
        return "idle";
    case SM03_MACHINEREF_STATE_RUNNING:
        return "running";
    case SC_STATE_INVALID:
        return "SC_STATE_INVALID";
    default:
        return "SC_STATE_UNKNOWN";
    }
}

const char *sm03_machineref_event_name(sc_event_id_t event)
{
    switch (event) {
    case SC_EVENT_COMPLETION:
        return "SC_EVENT_COMPLETION";
    case SC_EVENT_INVALID:
        return "SC_EVENT_INVALID";
    default:
        return "SC_EVENT_UNKNOWN";
    }
}
