/*
 * sm03/machine_ref_runner.c
 *
 * AUTO-GENERATED by sysmlc statix backend from state def 'SM03::MachineRef'. DO NOT EDIT.
 */

#include "sm03/machine_ref.h"

#include <stdio.h>
#include <string.h>

static bool sm03_machine_ref_event_from_name(const char *name, sc_event_id_t *event_id)
{
    if ((name == NULL) || (event_id == NULL)) {
        return false;
    }
    return false;
}

int main(int argc, char **argv)
{
    sm03_machine_ref_context_t ctx;
    sm03_machine_ref_t sm;
    sc_status_t status;
    int i;

    sm03_machine_ref_context_init(&ctx);
    status = sm03_machine_ref_init(&sm, &ctx);
    (void)printf("init status=%s state=%s final=%d ctx.enabled=%d\n", sc_status_str(status),
                 sm03_machine_ref_state_name(sm03_machine_ref_get_state(&sm)), (int)sm03_machine_ref_is_final(&sm), (int)ctx.enabled);
    if (status != SC_STATUS_OK) {
        return 1;
    }

    for (i = 1; i < argc; ++i) {
        sc_event_id_t event_id = SC_EVENT_INVALID;
        if (!sm03_machine_ref_event_from_name(argv[i], &event_id)) {
            (void)fprintf(stderr, "unknown event: %s\n", argv[i]);
            return 2;
        }
        status = sm03_machine_ref_post(&sm, event_id);
        (void)printf("event %s status=%s state=%s final=%d ctx.enabled=%d\n", argv[i],
                     sc_status_str(status), sm03_machine_ref_state_name(sm03_machine_ref_get_state(&sm)), (int)sm03_machine_ref_is_final(&sm), (int)ctx.enabled);
        if ((status != SC_STATUS_OK) && (status != SC_STATUS_NO_TRANSITION)) {
            return 1;
        }
    }
    return 0;
}
